import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const workspace = readFileSync(join(ROOT, "js", "workspace.js"), "utf8");
const selector = readFileSync(join(ROOT, "js", "prompt_selector.js"), "utf8");
const providers = readFileSync(join(ROOT, "js", "lib", "control_providers.js"), "utf8");
const components = readFileSync(join(ROOT, "js", "lib", "workspace_components.js"), "utf8");
const libraryStore = readFileSync(join(ROOT, "js", "lib", "library_store.js"), "utf8");
const imagePreview = readFileSync(join(ROOT, "js", "lib", "image_preview.js"), "utf8");
const promptEntryDetails = readFileSync(join(ROOT, "js", "lib", "prompt_entry_details.js"), "utf8");
const categoryColor = readFileSync(join(ROOT, "js", "lib", "category_color.js"), "utf8");
const ui = readFileSync(join(ROOT, "js", "lib", "ui.js"), "utf8");
const uiStyles = readFileSync(join(ROOT, "js", "lib", "ui.css"), "utf8");
const theme = readFileSync(join(ROOT, "js", "lib", "theme.css"), "utf8");
const workspaceIcon = readFileSync(join(ROOT, "js", "assets", "aaalice-workspace.svg"), "utf8");

test("workspace is an official left sidebar with reusable component boundaries", () => {
	assert.match(workspace, /registerSidebarTab/);
	assert.match(workspace, /id: TAB_ID/);
	assert.match(workspace, /createWorkspaceShell/);
	assert.match(components, /segmentedControl/);
	assert.match(workspace, /createSectionCard/);
	assert.match(workspace, /createControlCard/);
	assert.match(workspace, /app\.graph\.extra|graph\.extra/);
});

test("shared dialogs mount immediately without obsolete open calls", () => {
	assert.match(ui, /document\.body\.append\(overlay\)/);
	assert.doesNotMatch(workspace, /dialog\.open\(\)/);
	assert.doesNotMatch(selector, /dialog\.open\(\)/);
	assert.match(workspace, /function openCardActions[\s\S]*?dialog = createDialog/);
});

test("node context-menu add is independent from layout edit mode", () => {
	assert.match(workspace, /function patchNodeMenu/);
	assert.match(workspace, /📌 Add controls to sidebar/);
	const menuBody = workspace.match(/function patchNodeMenu[\s\S]*?\n}/)?.[0] || "";
	assert.doesNotMatch(menuBody, /editMode/);
	assert.match(workspace, /editMode \?[^\n]*Done/);
});

test("providers cover generic, Aaalice and public subgraph widgets by stable host identity", () => {
	assert.match(providers, /HOST_ID_PROPERTY/);
	assert.match(providers, /aaalice-parameter/);
	assert.match(providers, /generic-widget/);
	assert.match(providers, /subgraph-widget/);
	assert.match(providers, /isPromotedWidget/);
	assert.match(providers, /repairDuplicateHostIds/);
	assert.doesNotMatch(providers, /setInterval|setTimeout\([^)]*resolve/);
});

test("numeric control gestures preview live inside one graph history boundary", () => {
	assert.match(providers, /pointerdown/);
	assert.match(providers, /setValue\(next, \{ transaction: false \}\)/);
	assert.match(providers, /pointerup/);
	assert.match(providers, /beforeChange/);
	assert.match(providers, /afterChange/);
});

test("PromptSelector injects live library text and exposes inline weight management", () => {
	assert.match(selector, /materializePromptPayload/);
	assert.match(selector, /selection_payload_json/);
	assert.match(selector, /createSelectableImagePreview/);
	assert.match(imagePreview, /input\.type = "checkbox"/);
	assert.doesNotMatch(selector, /openSelectedEditor|aa-prompt-selected-editor|draggable: true/);
	assert.match(selector, /function promptWeightControl/);
	assert.match(selector, /event\.deltaY < 0/);
	assert.match(selector, /event\.shiftKey \? \.01 : \.1/);
	assert.match(selector, /if \(value !== 1\) commit\(1, true\)/);
	assert.match(selector, /_aaalicePromptWeightFocusEntryId/);
	assert.match(selector, /Prompt separator/);
	assert.match(selector, /openWorkspace\("library"\)/);
	assert.match(selector, /aa-prompt-selector-footer-actions/);
});

test("workspace uses event-driven refresh without polling", () => {
	assert.match(workspace, /addEventListener\("graphChanged"/);
	assert.match(workspace, /requestAnimationFrame/);
	assert.doesNotMatch(workspace, /setInterval/);
});

test("dashboard and library searches share a collapsible event-driven control", () => {
	assert.match(components, /export function createCollapsibleSearch/);
	assert.match(components, /aria-expanded/);
	assert.match(components, /event\.key === "Escape"/);
	assert.match(components, /queueMicrotask/);
	assert.match(workspace, /workspaceViewState = \{/);
	assert.match(workspace, /dashboard: \{ query: "", searchOpen: false, focusSearch: false \}/);
	assert.match(workspace, /viewState\.searchOpen = open; viewState\.focusSearch = open/);
	assert.doesNotMatch(workspace, /container\._aaalice(?:Dashboard|Library)(?:Query|SearchOpen|SearchShouldFocus)/);
	assert.match(workspace, /disabled: !page \|\| editMode/);
	assert.match(workspace, /sectionElement\.dataset\.searchText/);
	assert.match(workspace, /applyDashboardSearch\(value\)/);
	assert.match(workspace, /library: \{ query: "", searchOpen: false, focusSearch: false/);
	assert.match(workspace, /onInput: \(value\) => \{ query = value; viewState\.query = value; drawEntries\(\)/);
	assert.match(theme, /\.aa-workspace-search \{/);
	assert.match(workspace, /createWorkspaceToolbar\(searchOpen \? \[search\.panel\]/);
	assert.doesNotMatch(workspace, /container\.append\(toolbar, \.\.\.\(search\.panel/);
	assert.match(theme, /\.aa-dashboard-toolbar\.is-searching, \.aa-library-toolbar\.is-searching/);
	assert.match(theme, /@keyframes aa-workspace-search-open/);
	assert.match(theme, /\.aa-dashboard-body\.is-searching/);
});

test("PromptSelector can open the official sidebar directly on library management", () => {
	assert.match(workspace, /export function openWorkspace/);
	assert.match(workspace, /sidebar\.activeSidebarTabId = TAB_ID/);
	assert.match(workspace, /activeWorkspace = view/);
	assert.doesNotMatch(selector, /querySelector\([^\n]*sidebar|\.click\(\)/);
	assert.match(workspace, /export async function openPromptLibraryEntryEditor\(entryId\)/);
	assert.match(workspace, /snapshot\.entries\.find\(\(item\) => item\.id === entryId\)/);
	assert.match(workspace, /entryEditor\(entry\)/);
	assert.match(selector, /openPromptLibraryEntryEditor\(entry\.id\)/);
	assert.match(selector, /className: "aa-prompt-selector-edit"/);
	assert.match(selector, /className: `aa-prompt-selector-favorite\$\{isFavorite \? " is-active" : ""\}`/);
	assert.match(selector, /openFavoritePicker\(entry\)/);
	assert.match(selector, /updateEntry\(entry\.id, \{ collectionIds: \[\] \}\)/);
	assert.match(selector, /addCollectionId: target\.value/);
	assert.match(selector, /className: "aa-prompt-selector-row-actions"/);
	assert.match(selector, /event\.preventDefault\(\); event\.stopPropagation\(\); closePromptEntryDetails\(\)/);
	assert.match(theme, /\.aa-prompt-selector-row:hover \.aa-prompt-selector-row-actions \.aa-ui-button/);
	assert.match(theme, /\.aa-prompt-selector-edit \{ color: var\(--aa-ui-accent\); \}/);
	assert.match(theme, /\.aa-prompt-selector-favorite \{[^}]*color: var\(--aa-ui-warning\);/);
	assert.match(theme, /\.aa-prompt-selector-favorite\.is-active \{[^}]*background: transparent;[^}]*box-shadow: none;/);
	assert.match(theme, /\.aa-prompt-selector-favorite\.is-active \.aa-ui-icon \{ fill: currentColor; \}/);
});

test("workspace visual hierarchy uses a compact shell, dedicated icon and active section rail", () => {
	assert.match(workspace, /icon: "aaalice-workspace-sidebar-icon"/);
	assert.match(workspace, /element\.classList\.add\("aa-workspace-host"\)/);
	assert.match(theme, /\.aa-workspace-host \{[^}]*height: 100%;[^}]*min-height: 0;[^}]*overflow: hidden;/);
	assert.match(theme, /\.aa-workspace \{[^}]*flex: 1;/);
	assert.match(theme, /\.aaalice-workspace-sidebar-icon[\s\S]*mask: url\("\.\.\/assets\/aaalice-workspace\.svg"\)/);
	assert.match(workspaceIcon, /viewBox="0 0 24 24"/);
	assert.match(workspaceIcon, /stroke-linecap="round"/);
	assert.doesNotMatch(workspaceIcon, /<circle/);
	assert.match(workspace, /IntersectionObserver/);
	assert.match(workspace, /_aaaliceSectionObserver\?\.disconnect/);
	assert.doesNotMatch(components, /aa-workspace-brand/);
	assert.match(components, /ariaLabel: title/);
	assert.match(components, /root\.dataset\.workspace = activeTab/);
	assert.match(components, /root\.dataset\.workspace = value/);
	assert.match(theme, /\.aa-workspace\[data-workspace="library"\] \{[^}]*--aa-ui-accent: var\(--aa-workspace-library-accent\)/);
	assert.match(theme, /--aa-ui-accent-soft: color-mix/);
	assert.match(theme, /--aa-ui-focus: var\(--aa-workspace-library-accent\)/);
	assert.match(theme, /\.aa-workspace-tabs\[data-value="library"\]/);
	assert.match(theme, /\.aa-workspace-tabs \{[^}]*display: grid;[^}]*overflow: hidden;/);
	assert.match(theme, /transform \.2s cubic-bezier/);
	assert.doesNotMatch(workspace.match(/function renderWorkspace[\s\S]*?\n}/)?.[0] || "", /scheduleRender/);
	assert.match(components, /aa-control-card-indicator/);
	assert.match(theme, /\.aa-dashboard-dot\.is-active/);
});

test("PromptSelector exposes scannable selected and category states", () => {
	assert.match(selector, /aa-prompt-selector-toolbar/);
	assert.match(selector, /aa-prompt-selector-search-toggle/);
	assert.match(selector, /aa-prompt-selector-search/);
	assert.match(selector, /queueMicrotask/);
	assert.match(selector, /list\._aaaliceVirtualList\?\.setItems\(filteredEntries\(node, stateFor\(node\)\), \{ preserveScroll: false \}\)/);
	assert.match(selector, /mountPromptEntries/);
	assert.match(selector, /mountVirtualList/);
	assert.match(selector, /root\.append\(toolbar, list, footer\);\s*list\.scrollTop = listScrollTop;\s*virtualList\.refresh\(\);/s);
	assert.match(selector, /createSelectableImagePreview/);
	assert.match(imagePreview, /aa-image-preview-selection/);
	assert.match(imagePreview, /icon\("statusCheck"\)/);
	assert.match(selector, /aa-prompt-selector-title/);
	assert.match(selector, /bindPromptEntryDetails\(copy, entry\)/);
	assert.match(promptEntryDetails, /promptDetailsTooltip = createTooltip/);
	assert.match(promptEntryDetails, /PROMPT_DETAILS_HOVER_DELAY = 600/);
	assert.match(selector, /selectionSummaryTooltip = createTooltip/);
	assert.match(selector, /bindSelectionSummary\(categoryFilter\.control/);
	assert.match(selector, /bindSelectionSummary\(summary/);
	assert.match(selector, /categorySelectionSummary/);
	assert.match(selector, /selectedPromptSummary/);
	assert.match(promptEntryDetails, /aa-prompt-entry-details-prompt/);
	assert.match(promptEntryDetails, /collectionItems\(entry\.collections/);
	assert.match(selector, /aa-prompt-selector-summary/);
	assert.match(selector, /aa-prompt-selector-count/);
	assert.match(selector, /_aaalicePromptSelectedOnly/);
	assert.match(selector, /"aria-pressed": String\(selectedOnly\)/);
	assert.match(selector, /entries\.filter\(\(entry\) => selectedIds\.has\(entry\.id\)\)/);
	assert.match(selector, /countPromptSelectionsByCategory/);
	assert.match(selector, /aa-prompt-selector-clear-action/);
	assert.match(selector, /state\.selections\.length \? button/);
	assert.match(selector, /mutate\(node, clearPromptSelections\)/);
	assert.match(selector, /aa-prompt-selector-empty/);
	assert.match(selector, /isSelected \? " is-selected"/);
	assert.match(theme, /grid-template-columns: repeat\(2, minmax\(0, 1fr\)\) 34px/);
	assert.match(theme, /\.aa-prompt-selector-toolbar\.is-searching \{ grid-template-columns: minmax\(0, 1fr\); \}/);
	assert.match(theme, /\.dom-widget:has\(> \.aa-prompt-selector\) \{[^}]*position: relative;[^}]*min-height: 240px;[^}]*overflow: hidden;[^}]*pointer-events: none !important;/);
	assert.match(theme, /\.aa-prompt-selector \{[^}]*position: absolute;[^}]*inset: 0;[^}]*min-height: 0;[^}]*overflow: hidden;/);
	assert.match(theme, /\.aa-prompt-selector-list \{[^}]*min-height: 0;[^}]*overflow: auto;/);
	assert.match(theme, /\.aa-prompt-selector\.is-resizing, \.aa-prompt-selector\.is-resizing \* \{ pointer-events: none !important; \}/);
	assert.match(theme, /\.aa-prompt-selector-row\.is-selected/);
	assert.match(theme, /\.aa-prompt-selector-row \{[^}]*grid-template-columns: 38px minmax\(0, 1fr\);/);
	assert.match(theme, /\.aa-prompt-selector-row-actions \{[^}]*position: absolute;/);
	assert.match(theme, /--aa-prompt-row-surface: var\(--aa-ui-accent-soft\)/);
	assert.match(theme, /linear-gradient\(90deg, transparent, var\(--aa-prompt-row-surface\) 28%\)/);
	assert.doesNotMatch(theme, /aa-prompt-selector-row-actions \{ background:[^}]*aa-ui-surface/);
	assert.match(theme, /\.aa-prompt-selector-row:has\(\.aa-prompt-selector-favorite\.is-active\) \.aa-prompt-selector-copy \{ padding-right: 62px; \}/);
	assert.match(theme, /\.aa-prompt-selector-row\.is-selected:hover \.aa-prompt-selector-copy/);
	assert.match(theme, /\.aa-prompt-selector-weight \{[^}]*cursor: ns-resize;/);
	assert.match(theme, /\.aa-prompt-selector-summary\.is-active/);
	assert.match(uiStyles, /\.aa-image-preview-selectable:has\(input:checked\)/);
	assert.match(uiStyles, /\.aa-image-preview-selectable \.aa-image-preview-selection\s*\{[^}]*background:\s*color-mix\(in srgb, var\(--aa-ui-accent\) 18%, transparent\)/s);
	assert.match(uiStyles, /\.aa-image-preview-selectable \.aa-image-preview-selection > \.aa-ui-icon\s*\{[^}]*border:\s*0;[^}]*background:\s*transparent;[^}]*color:\s*var\(--aa-ui-on-media\);[^}]*stroke-width:\s*2\.5/s);
	assert.match(uiStyles, /\.aa-image-preview-selectable:has\(input:checked\) \.aa-image-preview-media > img\s*\{[^}]*filter:\s*saturate\(\.92\) brightness\(\.9\)/s);
	assert.match(theme, /\.aa-prompt-entry-details-tooltip/);
	assert.match(theme, /\.aa-prompt-selection-tooltip/);
	assert.match(theme, /\.aa-prompt-selection-summary > ol/);
	assert.match(uiStyles, /\.aa-ui-tooltip\s*\{[^}]*pointer-events:\s*none/s);
	assert.doesNotMatch(theme.match(/\.aa-image-preview-tooltip\s*\{[^}]*\}/s)?.[0] || "", /pointer-events/);
	assert.doesNotMatch(theme.match(/\.aa-prompt-entry-details-tooltip\s*\{[^}]*\}/s)?.[0] || "", /pointer-events/);
	assert.doesNotMatch(promptEntryDetails, /aa-prompt-entry-details-tooltip[^\n]*interactive:\s*true/);
	assert.match(theme, /\.aa-prompt-entry-details-prompt > p, \.aa-prompt-entry-details-note > p\s*\{[^}]*white-space:\s*pre-wrap/s);
});

test("filter dropdowns reuse the shared animated select control", () => {
	assert.match(ui, /export function selectControl/);
	assert.match(ui, /aria-expanded/);
	assert.match(ui, /icon\("moveDown"/);
	assert.match(selector, /promptFilterSelect/);
	assert.match(selector, /selectControl\(\{/);
	assert.match(workspace, /className: "aa-library-filter-select"/);
	assert.match(uiStyles, /\.aa-ui-select\.is-open \.aa-ui-select__arrow/);
	assert.match(uiStyles, /padding-right: 38px/);
	assert.match(ui, /syncOptionColor/);
	assert.match(ui, /--aa-ui-select-option-color/);
	assert.match(categoryColor, /export function categorySelectOption/);
	assert.match(selector, /value: option\.id, color: option\.color/);
	assert.match(workspace, /categories\.map\(categorySelectOption\)/);
});

test("workspace empty states and compact action bars keep narrow sidebars deliberate", () => {
	assert.match(components, /pages\.length \? "" : " is-empty"/);
	assert.match(workspace, /aa-dashboard-toolbar/);
	assert.match(workspace, /aa-library-toolbar/);
	assert.match(workspace, /iconName: "upload", label: t\("aaalice\.workspace\.preset\.export"/);
	assert.match(workspace, /iconName: "download", label: t\("aaalice\.workspace\.preset\.import"/);
	assert.match(workspace, /iconName: "upload", label: selected\.size[\s\S]*libraryUi\.export/);
	assert.match(workspace, /iconName: "download", label: t\("aaalice\.workspace\.libraryUi\.import"/);
	assert.match(workspace, /aa-workspace-empty aa-dashboard-empty/);
	assert.match(workspace, /aa-workspace-empty aa-library-empty/);
	assert.match(theme, /\.aa-dashboard-pages\.is-empty \{ display: none; \}/);
	assert.match(theme, /\.aa-library-filters \{ display: grid; grid-template-columns: minmax\(0, 1fr\) minmax\(0, 1fr\);/);
});

test("library rows keep a stable thumbnail column and distinguish entry actions", () => {
	assert.match(workspace, /createSelectableImagePreview/);
	assert.match(workspace, /aa-library-entry-preview/);
	assert.doesNotMatch(workspace, /checkbox\.type = "checkbox"/);
	assert.match(workspace, /mountVirtualList/);
	assert.match(workspace, /closeImagePreview/);
	assert.match(workspace, /className: "aa-library-entry-edit"/);
	assert.match(workspace, /className: "aa-library-entry-delete"/);
	assert.match(workspace, /el\("label", \{ className: "aa-library-entry-copy"/);
	assert.match(workspace, /for: `aa-library-entry-\$\{entry\.id\}`/);
	assert.match(workspace, /preview\.input\.click\(\)/);
	assert.match(workspace, /bindPromptEntryDetails\(copy, entry\)/);
	assert.match(workspace, /closePromptEntryDetails\(\)/);
	assert.match(theme, /\.aa-library-entry \{[^}]*grid-template-columns: 48px minmax\(0, 1fr\) auto/);
	assert.match(theme, /\.aa-library-entry\.is-selected/);
	assert.match(uiStyles, /\.aa-image-preview-selectable:has\(input:checked\) \.aa-image-preview-selection/);
	assert.match(theme, /\.aa-library-entry-copy \{[^}]*justify-content: center/);
	assert.match(theme, /\.aa-library-entry-edit:hover/);
	assert.match(theme, /\.aa-library-entry-delete:hover/);
	assert.match(theme, /\.aa-image-preview-large/);
	assert.match(theme, /\.aa-image-preview-large > img\s*\{[^}]*width:\s*auto[^}]*max-height:/s);
	assert.match(theme, /\.aa-image-preview-large > strong\s*\{[^}]*position:\s*absolute[^}]*background:\s*color-mix\([^}]*transparent\)/s);
	assert.match(imagePreview, /IMAGE_PREVIEW_HOVER_DELAY = 600/);
	assert.match(imagePreview, /addEventListener\("load", previewTooltip\.reposition/);
});

test("library selection actions operate on model data instead of rendered rows", () => {
	assert.doesNotMatch(workspace, /openBatchEdit|libraryUi\.batch|Edit selected entries/);
	assert.match(workspace, /className: "aa-library-selection-toggle"/);
	assert.match(workspace, /for \(const entry of visibleEntries\) selected\.add\(entry\.id\)/);
	assert.match(workspace, /if \(clearsSelection\) selected\.clear\(\)/);
	assert.match(workspace, /visibleEntries\.every\(\(entry\) => selected\.has\(entry\.id\)\)/);
	assert.match(workspace, /selectionToggle\.replaceChildren\(icon\(clearsSelection \? "close" : "statusCheck"\)/);
	assert.match(workspace, /selectionToggle\.classList\.toggle\("is-clear", clearsSelection\)/);
	assert.doesNotMatch(workspace, /querySelectorAll\([^\n]*aa-library-entry/);
	assert.match(theme, /\.aa-library-selection-actions/);
	assert.match(theme, /\.aa-library-selection-toggle\.is-clear:hover:not\(:disabled\)/);
	assert.match(workspace, /function openMoveSelected\(selected\)/);
	assert.match(workspace, /const entryIds = \[\.\.\.selected\]/);
	assert.match(workspace, /batchEntries\(\{ entryIds, categoryId: target\.value === "__none__" \? null : target\.value \}\)/);
	assert.match(workspace, /className: "aa-library-move-selected"/);
	assert.match(workspace, /moveSelected\.disabled = selected\.size === 0/);
	assert.match(theme, /\.aa-library-move-selected:hover:not\(:disabled\)/);
	assert.match(workspace, /className: "aa-library-export-selected"/);
	assert.match(workspace, /openLibraryExport\(\{ selected, categoryId, collectionId \}\)/);
	assert.match(workspace, /className: "aa-library-delete-selected"/);
	assert.match(workspace, /promptLibraryStore\.deleteEntries\(entryIds\)/);
	assert.match(workspace, /danger: true/);
	assert.match(theme, /\.aa-library-delete-selected:hover:not\(:disabled\)/);
});

test("prompt entry editor prioritizes prompt content and uses shared themed controls", () => {
	assert.match(workspace, /className: "aa-library-entry-dialog"/);
	assert.match(workspace, /size: "md"/);
	assert.match(workspace, /className: "aa-library-entry-section is-content"/);
	assert.match(workspace, /className: "aa-library-entry-lower"/);
	assert.match(workspace, /listboxControl\(\{/);
	assert.match(workspace, /multiSelectControl\(\{/);
	assert.match(workspace, /collectionIds: collections\.values\(\)/);
	assert.match(workspace, /className: "aa-library-entry-preview-card"/);
	assert.match(workspace, /className: "aa-library-entry-preview-overlay"/);
	assert.match(workspace, /removePreviewRequested/);
	assert.match(workspace, /URL\.revokeObjectURL\(selectedPreviewUrl\)/);
	assert.match(ui, /export function listboxControl/);
	assert.match(ui, /role: "listbox"/);
	assert.match(ui, /role: "option"/);
	assert.match(ui, /export function multiSelectControl/);
	assert.match(ui, /role: "group"/);
	assert.match(ui, /setAttribute\("aria-pressed", String\(active\)\)/);
	assert.match(uiStyles, /\.aa-ui-multiselect__option\.is-selected/);
	assert.match(uiStyles, /\.aa-ui-listbox__option\.is-selected/);
	assert.match(theme, /\.aa-library-entry-dialog \{ width: min\(820px/);
	assert.match(theme, /\.aa-library-entry-prompt-field textarea \{ min-height: 238px/);
	assert.match(theme, /@media \(max-width: 720px\)[\s\S]*\.aa-library-entry-lower \{ grid-template-columns: 1fr;/);
});

test("taxonomy management is a complete single-dialog workspace", () => {
	assert.match(workspace, /function openTaxonomyManager/);
	assert.doesNotMatch(workspace, /function openTaxonomyChooser|function manageTaxonomy/);
	assert.match(workspace, /segmentedControl\(\{/);
	assert.match(workspace, /aa-taxonomy-list/);
	assert.match(workspace, /editingId === item\.id/);
	assert.match(workspace, /aa-taxonomy-footer/);
	assert.match(workspace, /usageCount\(item\)/);
	assert.match(theme, /\.aa-taxonomy-dialog/);
	assert.match(theme, /\.aa-taxonomy-tabs \{[^}]*margin-inline: auto/);
	assert.match(theme, /\.aa-taxonomy-tabs\[data-value="collections"\]/);
	assert.match(theme, /--aa-taxonomy-tab-color/);
	assert.match(theme, /\.aa-taxonomy-row\.is-editing/);
	assert.match(workspace, /colorInput\.type = "color"/);
	assert.match(workspace, /updateCategory\(item\.id, \{ name, color: colorInput\.value \}\)/);
	assert.match(workspace, /aa-taxonomy-color-swatch/);
	assert.match(components, /leading = null/);
	assert.match(categoryColor, /export function applyCategoryColor/);
	assert.match(theme, /\.aa-taxonomy-color-swatch/);
	assert.match(theme, /\.is-category-colored/);
	assert.match(workspace, /className: "aa-taxonomy-edit-action"/);
	assert.match(workspace, /className: "aa-taxonomy-delete-action"/);
	assert.match(workspace, /deleteCategoryTitle/);
	assert.match(workspace, /confirmLabel: t\("aaalice\.common\.delete"/);
	assert.match(workspace, /variant: "danger"/);
	assert.match(uiStyles, /\.aa-ui-button--danger/);
	const saveBody = workspace.match(/const saveItem = async[\s\S]*?\n\t};/)?.[0] || "";
	assert.match(saveBody, /updateCategory/);
	assert.doesNotMatch(saveBody, /deleteCategory|deleteCollection/);
	const removeBody = workspace.match(/const remove = async[\s\S]*?\n\t};/)?.[0] || "";
	assert.match(removeBody, /deleteCategory/);
	assert.match(removeBody, /danger: true/);
});

test("import and export use one reusable review flow with explicit outcomes", () => {
	assert.match(components, /export function createTransferHero/);
	assert.match(components, /export function createTransferStats/);
	assert.match(components, /export function createTransferSection/);
	assert.match(components, /export function createTransferResult/);
	assert.match(workspace, /function openLibraryExport/);
	assert.match(workspace, /function openDashboardExport/);
	assert.match(workspace, /createTransferSection\(\{ title: t\("aaalice\.workspace\.transfer\.conflictDecisions"/);
	assert.match(workspace, /disabled: groups\.invalid\.length > 0/);
	assert.match(workspace, /presetNeedsReview/);
	assert.match(workspace, /createTransferResult\(\{ title: t\("aaalice\.workspace\.transfer\.importComplete"/);
	assert.match(libraryStore, /importPreflight\(file, \{ signal \} = \{\}\)/);
	assert.match(libraryStore, /importApply\(token, resolutions = \{\}, \{ signal \} = \{\}\)/);
	assert.match(libraryStore, /discardImport\(token\)/);
	assert.match(libraryStore, /apiURL\(`\$\{ENDPOINT\}\/export\/\$\{encodeURIComponent\(result\.token\)\}`\)/);
	assert.doesNotMatch(workspace, /response\.blob\(\)/);
	assert.match(theme, /\.aa-transfer-scope\.is-selected/);
	assert.match(theme, /\.aa-transfer-section\[open\] > summary > \.aa-ui-icon/);
	assert.match(theme, /@keyframes aa-transfer-loading/);
});
