import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const workspace = readFileSync(join(ROOT, "js", "workspace.js"), "utf8");
const selector = readFileSync(join(ROOT, "js", "prompt_selector.js"), "utf8");
const providers = readFileSync(join(ROOT, "js", "lib", "control_providers.js"), "utf8");
const widgetAdapters = readFileSync(join(ROOT, "js", "lib", "widget_control_adapters.js"), "utf8");
const nodeControlMenu = readFileSync(join(ROOT, "js", "lib", "node_control_menu.js"), "utf8");
const workspaceControls = readFileSync(join(ROOT, "js", "lib", "workspace_controls.js"), "utf8");
const imageCompareControl = readFileSync(join(ROOT, "js", "lib", "controls", "image_compare.js"), "utf8");
const numericControl = readFileSync(join(ROOT, "js", "lib", "controls", "numeric.js"), "utf8");
const choiceControl = readFileSync(join(ROOT, "js", "lib", "controls", "choice.js"), "utf8");
const booleanControl = readFileSync(join(ROOT, "js", "lib", "controls", "boolean.js"), "utf8");
const taglistControl = readFileSync(join(ROOT, "js", "lib", "controls", "taglist.js"), "utf8");
const imageControl = readFileSync(join(ROOT, "js", "lib", "controls", "image.js"), "utf8");
const controlRegistry = readFileSync(join(ROOT, "js", "lib", "controls", "registry.js"), "utf8");
const components = readFileSync(join(ROOT, "js", "lib", "workspace_components.js"), "utf8");
const uiSource = readFileSync(join(ROOT, "js", "lib", "ui.js"), "utf8");
const dashboardComponents = readFileSync(join(ROOT, "js", "lib", "dashboard_components.js"), "utf8");
const dashboardInteractions = readFileSync(join(ROOT, "js", "lib", "dashboard_interactions.js"), "utf8");
const dashboardCommands = readFileSync(join(ROOT, "js", "lib", "dashboard_commands.js"), "utf8");
const dashboardLayout = readFileSync(join(ROOT, "js", "lib", "dashboard_layout.js"), "utf8");
const dashboardSizing = readFileSync(join(ROOT, "js", "lib", "dashboard_sizing.js"), "utf8");
const dashboardSelection = readFileSync(join(ROOT, "js", "lib", "dashboard_selection.js"), "utf8");
const dashboardPresets = readFileSync(join(ROOT, "js", "lib", "dashboard_presets.js"), "utf8");
const dashboardPresetRuntime = readFileSync(join(ROOT, "js", "lib", "dashboard_preset_runtime.js"), "utf8");
const groupNavigation = readFileSync(join(ROOT, "js", "lib", "group_navigation.js"), "utf8");
const groupNavigationModel = readFileSync(join(ROOT, "js", "lib", "group_navigation_model.js"), "utf8");
const libraryStore = readFileSync(join(ROOT, "js", "lib", "library_store.js"), "utf8");
const imagePreview = readFileSync(join(ROOT, "js", "lib", "image_preview.js"), "utf8");
const imageUpload = readFileSync(join(ROOT, "js", "lib", "image_upload.js"), "utf8");
const promptEntryDetails = readFileSync(join(ROOT, "js", "lib", "prompt_entry_details.js"), "utf8");
const categoryColor = readFileSync(join(ROOT, "js", "lib", "category_color.js"), "utf8");
const ui = readFileSync(join(ROOT, "js", "lib", "ui.js"), "utf8");
const uiStyles = readFileSync(join(ROOT, "js", "lib", "ui.css"), "utf8");
const theme = readFileSync(join(ROOT, "js", "lib", "theme.css"), "utf8");
const workspaceIcon = readFileSync(join(ROOT, "js", "assets", "aaalice-workspace.svg"), "utf8");
const enLocale = readFileSync(join(ROOT, "locales", "en", "main.json"), "utf8");
const zhLocale = readFileSync(join(ROOT, "locales", "zh", "main.json"), "utf8");

test("native image comparison is a localized accessible sidebar media control", () => {
	assert.match(widgetAdapters, /id: "comfy-image-compare"/);
	assert.match(widgetAdapters, /presettable: false/);
	assert.match(imageCompareControl, /role: "slider"/);
	assert.match(imageCompareControl, /aria-valuenow/);
	assert.match(imageCompareControl, /beforeImages/);
	assert.match(imageCompareControl, /afterImages/);
	assert.match(imageCompareControl, /createDialog/);
	assert.match(imageCompareControl, /aa-image-compare-dialog/);
	assert.match(imageCompareControl, /iconName: "zoomIn"/);
	assert.match(imageCompareControl, /iconName: "zoomOut"/);
	assert.match(imageCompareControl, /viewport\.addEventListener\("click"/);
	assert.match(imageCompareControl, /draggable = false/);
	assert.match(imageCompareControl, /addEventListener\("dragstart", \(event\) => event\.preventDefault\(\)\)/);
	assert.match(imageCompareControl, /addEventListener\("wheel"/);
	assert.match(imageCompareControl, /addEventListener\("pointermove"/);
	assert.match(imageCompareControl, /MAX_ZOOM = 8/);
	assert.match(imageCompareControl, /destroy: \(\) => viewer\?\.requestClose/);
	assert.match(theme, /\.aa-image-compare__image\.is-before/);
	assert.match(theme, /clip-path: inset/);
	assert.doesNotMatch(imageCompareControl, /aa-image-compare__handle/);
	assert.doesNotMatch(theme, /\.aa-image-compare__handle/);
	assert.doesNotMatch(imageCompareControl, /aa-image-compare-viewer__handle/);
	assert.doesNotMatch(theme, /\.aa-image-compare-viewer__handle/);
	assert.match(imageCompareControl, /if \(event\.pointerType === "mouse"\) setPositionFromPointer\(event\)/);
	assert.match(imageCompareControl, /navigationGroup\(beforeCounter, beforeImages, "before"\)[\s\S]*?aa-image-compare-viewer__zoom[\s\S]*?navigationGroup\(afterCounter, afterImages, "after"\)/);
	assert.match(theme, /\.aa-image-compare-viewer__stage/);
	assert.match(theme, /--aa-image-compare-zoom/);
	assert.match(theme, /\.aa-image-compare-viewer__toolbar \{[^}]*display: grid;[^}]*grid-template-columns: minmax\(0, 1fr\) auto minmax\(0, 1fr\)/);
	assert.match(theme, /\.aa-image-compare-viewer__nav-group\.is-before \{ justify-self: start; \}/);
	assert.match(theme, /\.aa-image-compare-viewer__nav-group\.is-after \{ justify-self: end; \}/);
	assert.match(theme, /\.aa-image-compare-viewer__zoom \{[^}]*justify-self: center;/);
	assert.match(theme, /-webkit-user-drag: none/);
	for (const locale of [enLocale, zhLocale]) {
		assert.match(locale, /"imageCompare"/);
		assert.match(locale, /"slider"/);
		assert.match(locale, /"zoomIn"/);
		assert.match(locale, /"fit"/);
	}
});

test("workspace is an official left sidebar with reusable component boundaries", () => {
	assert.match(workspace, /registerSidebarTab/);
	assert.match(workspace, /title: t\("aaalice\.workspace\.sidebarTitle", "Aaalice"\)/);
	assert.match(workspace, /tooltip: t\("aaalice\.workspace\.title", "Aaalice Workspace"\)/);
	assert.match(workspace, /id: TAB_ID/);
	assert.match(workspace, /function installWorkspaceCanvasAutoClose/);
	assert.match(workspace, /canvas\.addEventListener\("click"/);
	assert.match(workspace, /!sidebarPinned && sidebar\.activeSidebarTabId === TAB_ID/);
	assert.match(workspace, /sidebar\.toggleSidebarTab\(TAB_ID\)/);
	assert.match(workspace, /createWorkspaceShell/);
	assert.match(components, /segmentedControl/);
	assert.match(components, /headerActions = \[\]/);
	assert.match(workspace, /const SIDEBAR_PIN_STORAGE_KEY = "aaalice\.workspace\.sidebarPinned"/);
	assert.match(workspace, /let sidebarPinned = loadSidebarPinned\(\)/);
	assert.match(workspace, /localStorage\?\.getItem\(SIDEBAR_PIN_STORAGE_KEY\)/);
	assert.match(workspace, /localStorage\?\.setItem\(SIDEBAR_PIN_STORAGE_KEY, String\(value\)\)/);
	assert.match(workspace, /saveSidebarPinned\(sidebarPinned\)/);
	assert.match(workspace, /className: "aa-workspace-pin"/);
	assert.match(workspace, /aria-pressed/);
	assert.match(workspace, /workspacePinTooltip\.show\(pinButton, pinLabel/);
	assert.match(theme, /\.aa-workspace-pin\.aa-ui-button\.is-active/);
	assert.match(workspace, /createDashboardGrid/);
	assert.match(workspace, /bindDashboardInteractions/);
	assert.match(workspace, /createControlCard/);
	assert.match(workspace, /app\.graph\.extra|graph\.extra/);
});

test("shared dialogs mount immediately without obsolete open calls", () => {
	assert.match(ui, /document\.body\.append\(overlay\)/);
	assert.match(ui, /const DEFAULT_DIALOG_SIZE = "compact"/);
	assert.match(ui, /size = DEFAULT_DIALOG_SIZE/);
	assert.match(ui, /confirmOnEnter = true/);
	assert.match(ui, /function dialogDefaultAction\(footer\)/);
	assert.match(ui, /data-aa-dialog-default/);
	assert.match(ui, /dialogAction\(footer, "\.aa-ui-button--primary"\)/);
	assert.match(ui, /dialogAction\(footer, "\.aa-ui-button--danger"\)/);
	assert.match(ui, /event\.key === "Enter" && confirmOnEnter/);
	assert.match(ui, /action\.click\(\)/);
	assert.match(ui, /event\.isComposing/);
	assert.match(ui, /textarea, select, \[contenteditable\]/);
	assert.match(ui, /event\.key === "Escape"/);
	assert.match(ui, /event\.key === "Escape" && open[\s\S]*?event\.stopPropagation\(\)[\s\S]*?setOpen\(false\)/);
	assert.match(ui, /requestClose\(null\)/);
	assert.match(ui, /onClose = null/);
	assert.match(ui, /try \{ onClose\?\.\(value\); \}/);
	assert.match(uiStyles, /\.aa-ui-dialog--compact \{ width: min\(420px, 96vw\); \}/);
	assert.doesNotMatch(workspace, /dialog\.open\(\)/);
	assert.doesNotMatch(selector, /dialog\.open\(\)/);
	assert.match(workspace, /function openCardActions[\s\S]*?dialog = createDialog/);
});

test("node context-menu add is independent from layout edit mode", () => {
	assert.match(workspace, /function patchNodeMenu/);
	assert.match(workspace, /📌 Add controls to sidebar/);
	const menuBody = workspace.match(/function patchNodeMenu[\s\S]*?\n}/)?.[0] || "";
	assert.doesNotMatch(menuBody, /editMode/);
	assert.match(menuBody, /installNodeControlMenu/);
	assert.match(nodeControlMenu, /listControls\(this\)/);
	assert.match(workspace, /editMode \?[^\n]*Done/);
});

test("integrates visual-group navigation into the existing workspace sidebar", () => {
	assert.match(workspace, /value: "groups"/);
	assert.match(workspace, /function renderGroupNavigation/);
	assert.match(workspace, /const GROUP_NAVIGATION_EXTRA_KEY = "aaaliceGroupNavigation"/);
	assert.match(workspace, /addGroupNavigationEntry/);
	assert.match(workspace, /openAddGroupNavigation/);
	assert.match(workspace, /navigateToVisualGroup\(app\.canvas, group, \{ offset, zoom \}\)/);
	assert.match(workspace, /aa-group-navigation-row/);
	assert.match(workspace, /openGroupNavigationSettings/);
	assert.match(workspace, /setGroupNavigationOffset/);
	assert.match(workspace, /setGroupNavigationZoom/);
	assert.match(workspace, /navigateFromWorkspace\(group, entry\.offset, entry\.zoom\)/);
	assert.match(workspace, /window\.addEventListener\("keydown", handleGroupNavigationShortcut, true\)/);
	assert.match(groupNavigationModel, /shortcutFromKeyboardEvent/);
	assert.match(groupNavigationModel, /Ctrl.*Alt.*Shift.*Meta/);
	assert.match(workspace, /scheduleRender\("groups"\)/);
	assert.match(groupNavigation, /animateToBounds/);
	assert.match(groupNavigation, /centerOnNode/);
	assert.match(theme, /\.aa-group-navigation-marker/);
	assert.match(enLocale, /"groupNavigation"/);
	assert.match(zhLocale, /"groupNavigation"/);
});

test("providers cover generic, Aaalice and public subgraph widgets by stable host identity", () => {
	assert.match(providers, /HOST_ID_PROPERTY/);
	assert.match(providers, /aaalice-parameter/);
	assert.match(providers, /generic-widget/);
	assert.match(providers, /subgraph-widget/);
	assert.match(providers, /listAdaptedWidgetControls/);
	assert.match(widgetAdapters, /registerWidgetControlAdapter/);
	assert.match(widgetAdapters, /comfy-native-widget/);
	assert.match(widgetAdapters, /valueType: definition\.valueType/);
	assert.match(widgetAdapters, /state: "empty", reason: "no-options"/);
	assert.doesNotMatch(widgetAdapters, /Boolean\(controlValueType\(widget\.value\)\)/);
	assert.match(widgetAdapters, /priority/);
	assert.match(widgetAdapters, /adapterId/);
	assert.match(providers, /repairDuplicateHostIds/);
	assert.doesNotMatch(providers, /setInterval|setTimeout\([^)]*resolve/);
	assert.doesNotMatch(providers, /document\.|addEventListener|createNumericEditor|createImageUploadControl|selectControl|toggleSwitch/);
	assert.match(controlRegistry, /renderControlAvailability/);
	assert.match(theme, /\.aa-control-card\.is-unavailable/);
	assert.match(theme, /\.aa-control-availability \{/);
});

test("numeric control gestures preview live inside one graph history boundary", () => {
	assert.match(numericControl, /pointerdown/);
	assert.match(workspaceControls, /setValue\(next, \{ transaction: false, transient: true \}\)/);
	assert.match(providers, /flushValue/);
	assert.match(providers, /node\._aaaliceParameterRedraw\?\.\(\)/);
	assert.match(numericControl, /pointerup/);
	assert.match(workspaceControls, /beforeChange/);
	assert.match(workspaceControls, /afterChange/);
	assert.match(workspaceControls, /createSharedControl\(spec/);
	assert.match(numericControl, /--aa-shared-range-progress/);
	assert.match(numericControl, /aa-shared-range aa-control-numeric-range/);
	assert.match(uiStyles, /\.aa-shared-range::\-webkit-slider-runnable-track/);
	assert.match(numericControl, /const accessories = \[valueButton\]/);
	assert.match(numericControl, /createNumericEditor/);
	assert.match(numericControl, /addEventListener\("wheel"/);
	assert.match(numericControl, /event\.shiftKey \? 10 : 1/);
	assert.match(numericControl, /passive: false/);
	assert.match(theme, /\.aa-control-numeric-value/);
	assert.match(uiStyles, /::-webkit-slider-runnable-track/);
	assert.match(components, /control\?\.headerAccessories/);
});

test("dashboard image controls share upload, drop, thumbnail, and preview behavior", () => {
	assert.match(imageControl, /renderImageControl/);
	assert.match(imageControl, /aa-control-image/);
	assert.match(imageControl, /createImageUploadControl\(\{/);
	assert.match(imageControl, /port\.commit\(null\)/);
	assert.match(imagePreview, /export function bindImagePreview/);
	assert.match(imageUpload, /export function isImageFile/);
	assert.match(imageUpload, /export async function uploadImageFile/);
	assert.match(imageUpload, /export function bindImageDropTarget/);
	assert.match(imageUpload, /export function createImageUploadControl/);
	assert.match(imageUpload, /bindImagePreview\(button, source,[^\n]*immediate: true/);
	assert.match(workspace, /notifyWorkspaceImageUpload/);
	assert.match(theme, /\.aa-image-upload-button > img\s*\{[^}]*object-fit:\s*cover/s);
	assert.match(theme, /\.aa-image-upload-button > img\s*\{[^}]*z-index:\s*0/s);
	assert.match(theme, /\.aa-image-upload-button\.has-image::before\s*\{[^}]*z-index:\s*1/s);
	assert.match(theme, /\.aa-image-upload-button\.has-image \.aa-image-upload-label\s*\{[^}]*margin-inline:\s*0 auto;[^}]*font-weight:\s*650;[^}]*text-align:\s*left/s);
	assert.match(theme, /\.aa-image-upload-button\.is-drop-target/);
	assert.match(theme, /\.aa-image-upload-control:hover \.aa-image-upload-clear/);
	assert.match(theme, /\.aa-image-upload-control\s*\{[^}]*height:\s*32px/s);
});

test("dashboard tag-list controls reuse the shared interactive chip editor", () => {
	assert.match(taglistControl, /createTagListControl\(\{/);
	assert.match(workspaceControls, /taglist: \{ \.\.\.availabilityLabels, \.\.\.\(labels\.taglist \|\| \{\}\) \}/);
	assert.match(workspaceControls, /createSharedControl\(spec/);
	assert.match(workspaceControls, /control\.dataset\.controlKind = view\.kind/);
	assert.match(theme, /\.aa-control-card \[data-control-tone\] \{ --aa-control-item-tone: var\(--aa-ui-accent\); \}/);
	assert.match(theme, /\.aa-taglist-control \{[^}]*display: flex;[^}]*height: 32px;[^}]*box-sizing: border-box;[^}]*overflow-x: auto;/);
	assert.match(theme, /\.aa-taglist-control::\-webkit-scrollbar \{ display: none; \}/);
	assert.match(theme, /\.aa-taglist-options \{ display: contents; \}/);
	assert.match(theme, /\.aaalice-pcp\.aaalice-pcp-node-root \.aa-taglist-control > input\.aa-taglist-input,[\s\S]*border: 0;[^}]*background: transparent;[^}]*box-shadow: none;/);
	assert.match(theme, /\.aa-taglist-chip\.is-selected/);
	assert.match(theme, /\.aa-taglist-chip\.is-disabled/);
	assert.match(theme, /\[data-control-tone="11"\]/);
	assert.match(taglistControl, /tagToneIndexes\(entries\)/);
	assert.match(workspace, /event\.detail\?\.workspaceRedraw !== false/);
});

test("seed lock state reuses one shared control across the node and dashboard", () => {
	const parameterPanel = readFileSync(join(ROOT, "js", "parameter_panel.js"), "utf8");
	assert.match(numericControl, /export function createSeedModeControl/);
	assert.match(numericControl, /control\.setLocked/);
	assert.match(numericControl, /aria-pressed/);
	assert.match(parameterPanel, /createSharedControl\(spec/);
	assert.match(workspaceControls, /createSharedControl\(spec/);
	assert.match(providers, /control_after_generate = locked \? "fixed" : "randomize"/);
	assert.match(providers, /adapted\.setSeedLocked\(locked\)/);
	assert.match(providers, /createSeedPresetPayload\(parameter\.value, parameter\.config\?\.control_after_generate\)/);
	assert.match(providers, /parameter\.config\.control_after_generate = decoded\.behavior/);
	assert.match(theme, /\.aa-control-seed-mode\.is-locked/);
	assert.match(theme, /\.aa-control-card:has\(\.aa-control-seed-mode\.is-locked\)/);
	assert.match(theme, /\.aa-control-card:has\(\.aa-control-seed-mode\.is-locked\) \.aa-control-numeric-value/);
});

test("dashboard enum and boolean controls reuse the shared themed controls", () => {
	assert.match(choiceControl, /selectControl\(\{/);
	assert.match(booleanControl, /toggleSwitch\(\{/);
	assert.match(booleanControl, /aa-control-boolean-dot/);
	assert.match(booleanControl, /aa-control-boolean-state/);
	assert.match(booleanControl, /root\.classList\.toggle\("is-on", current\)/);
	assert.match(booleanControl, /event\.target\.closest\("\.aa-ui-toggle"\)/);
	assert.match(booleanControl, /attrs: \{ "aria-hidden": "true" \}/);
	assert.match(controlRegistry, /AAALICE_CONTROL_RENDERERS/);
	assert.match(controlRegistry, /COMFY_CONTROL_RENDERERS/);
	assert.match(components, /root\.dataset\.controlKind/);
	assert.match(theme, /\.aa-control-choice-select/);
	assert.doesNotMatch(theme, /\.aa-control-card\[data-control-kind="choice"\] \{ --aa-dashboard-control-tone:/);
	assert.match(theme, /\.aa-control-card \.aa-control-choice-select \.aa-ui-select__native \{[^}]*font-size: 11px;[^}]*font-weight: 620;/);
	assert.match(theme, /\.aa-control-boolean/);
	assert.match(theme, /\.aa-control-boolean\.is-on \.aa-control-boolean-dot/);
	assert.match(theme, /\.aa-control-boolean:focus-within/);
});

test("control cards move management into an accessible context menu", () => {
	const cardBody = components.match(/export function createControlCard[\s\S]*?\n}/)?.[0] || "";
	assert.match(ui, /export function createContextMenu/);
	assert.match(ui, /role: "menu"/);
	assert.match(ui, /setAttribute\("role", "menuitem"\)/);
	assert.match(ui, /ArrowUp/);
	assert.match(ui, /window\.innerWidth - rect\.width/);
	assert.match(cardBody, /addEventListener\("contextmenu"/);
	assert.match(cardBody, /event\.key !== "ContextMenu"/);
	assert.match(cardBody, /preservesNativeEditing/);
	assert.doesNotMatch(cardBody, /iconButton\(/);
	assert.match(workspace, /function openCardActions/);
	assert.match(workspace, /createContextMenu\(\{ x, y/);
	assert.match(workspace, /danger: true/);
	assert.match(uiStyles, /\.aa-ui-context-menu__item\.is-danger/);
});

test("header-only seed controls do not stretch to the neighboring slider card", () => {
	assert.match(numericControl, /headerOnly: !hasRange/);
	assert.match(components, /control\?\.dataset\?\.headerOnly === "true"/);
	assert.match(theme, /\.aa-dashboard-grid-v2, \.aa-dashboard-group-grid \{[^}]*grid-auto-rows: 4px;[^}]*align-items: stretch;/);
	assert.match(theme, /\.aa-control-card\.is-header-only \{[^}]*padding-block: 7px;/);
	assert.match(theme, /\.aa-control-card\.is-header-only \.aa-control-numeric-value \{[^}]*min-width: 64px;[^}]*flex: 1;/);
	assert.match(theme, /\.aa-control-numeric-value \{[^}]*text-align: center;/);
});

test("PromptSelector injects live library text and exposes inline weight management", () => {
	assert.match(selector, /materializePromptPayload/);
	assert.match(selector, /selection_payload_json/);
	assert.match(selector, /createImagePreview/);
	assert.doesNotMatch(selector, /createSelectableImagePreview/);
	assert.match(imagePreview, /input\.type = "checkbox"/);
	assert.doesNotMatch(selector, /openSelectedEditor|aa-prompt-selected-editor|draggable: true/);
	assert.match(selector, /function promptWeightControl/);
	assert.match(selector, /event\.deltaY < 0/);
	assert.match(selector, /event\.shiftKey \? \.01 : \.1/);
	assert.match(selector, /if \(value !== 1\) commit\(1, true\)/);
	assert.match(selector, /_aaalicePromptWeightFocusEntryId/);
	assert.match(selector, /Prompt separator/);
	assert.match(selector, /openWorkspace\("library"\)/);
	assert.match(selector, /aa-prompt-selector-footer-actions/);
	assert.match(selector, /recordUsage\(\[\.\.\.usedEntryIds\]\)/);
	assert.match(selector, /_aaalicePromptRecentFirst !== false/);
	assert.match(selector, /aa-prompt-selector-recent-sort/);
});

test("workspace uses event-driven refresh without polling", () => {
	assert.match(workspace, /addEventListener\("graphChanged"/);
	assert.match(workspace, /requestAnimationFrame/);
	assert.doesNotMatch(workspace, /setInterval/);
});

test("dashboard and library searches share a collapsible event-driven control", () => {
	assert.match(components, /export function createCollapsibleSearch/);
	assert.match(components, /searchToggleButton\(\{ label, value, open, disabled/);
	assert.match(components, /input\.className = "aa-ui-search-input"/);
	assert.match(components, /iconName: "arrowRight"[^}]*className: "aa-ui-search-collapse"/);
	assert.match(uiSource, /export function searchToggleButton/);
	assert.doesNotMatch(uiSource, /searchApplied/);
	assert.match(uiSource, /control\.replaceChildren\(icon\("search"\)\)/);
	assert.match(uiSource, /className: "aa-ui-search-summary__query"/);
	assert.match(uiSource, /control\.setAttribute\("aria-expanded"/);
	assert.match(components, /event\.key === "Escape"/);
	assert.match(components, /queueMicrotask/);
	assert.match(workspace, /workspaceViewState = \{/);
	assert.match(workspace, /dashboard: \{ query: "", searchOpen: false, focusSearch: false, pageRailExpanded: false, selectedItemIds: new Set\(\)/);
	assert.match(workspace, /viewState\.searchOpen = open; viewState\.focusSearch = open/);
	assert.doesNotMatch(workspace, /if \(!open\) viewState\.query = ""/);
	assert.doesNotMatch(workspace, /container\._aaalice(?:Dashboard|Library)(?:Query|SearchOpen|SearchShouldFocus)/);
	assert.match(workspace, /disabled: !page \|\| editMode/);
	assert.match(workspace, /item\.dataset\.searchText/);
	assert.match(workspace, /applyDashboardSearch\(value\)/);
	assert.match(workspace, /library: \{ query: "", searchOpen: false, focusSearch: false/);
	assert.match(workspace, /onInput: \(value\) => \{ query = value; viewState\.query = value; drawEntries\(\)/);
	assert.match(theme, /\.aa-workspace-search \{/);
	assert.match(workspace, /createWorkspaceToolbar\(searchOpen \? \[search\.panel\]/);
	assert.doesNotMatch(workspace, /container\.append\(toolbar, \.\.\.\(search\.panel/);
	assert.match(theme, /\.aa-dashboard-toolbar\.is-searching, \.aa-library-toolbar\.is-searching/);
	assert.match(theme, /@keyframes aa-workspace-search-open/);
	assert.match(workspace, /pageRail\.hidden = Boolean\(needle\)/);
});

test("PromptSelector can open the official sidebar directly on library management", () => {
	assert.match(workspace, /export function openWorkspace/);
	assert.match(workspace, /sidebar\.activeSidebarTabId = TAB_ID/);
	assert.match(workspace, /activeWorkspace = view/);
	assert.doesNotMatch(selector, /querySelector\([^\n]*sidebar|\.click\(\)/);
	assert.match(workspace, /export async function openPromptLibraryEntryEditor\(entryId\)/);
	assert.match(workspace, /snapshot\.entries\.find\(\(item\) => item\.id === entryId\)/);
	assert.match(workspace, /entryEditor\(entry\)/);
	assert.match(selector, /openPromptLibraryEntryEditor\(entry\.id\)/);
	assert.match(selector, /preview\.addEventListener\("dblclick"/);
	assert.match(selector, /thumbnailEditHint/);
	assert.match(selector, /copy\.addEventListener\("click", \(\) => mutate/);
	assert.match(selector, /"aria-pressed": String\(isSelected\)/);
	assert.match(selector, /className: "aa-prompt-selector-edit"/);
	assert.match(selector, /className: `aa-prompt-selector-favorite\$\{isFavorite \? " is-active" : ""\}`/);
	assert.match(selector, /openFavoritePicker\(entry\)/);
	assert.match(selector, /updateEntry\(entry\.id, \{ collectionIds: \[\] \}\)/);
	assert.match(selector, /addCollectionId: target\.value/);
	assert.match(selector, /className: "aa-prompt-selector-row-actions"/);
	assert.match(selector, /event\.preventDefault\(\); event\.stopPropagation\(\); closePromptEntryDetails\(\)/);
	assert.match(theme, /\.aa-prompt-selector-row:hover \.aa-prompt-selector-row-actions \.aa-ui-button/);
	assert.match(theme, /\.aa-prompt-selector-edit \{ color: var\(--aa-ui-accent\); \}/);
	assert.match(theme, /\.aa-prompt-selector-favorite \{[^}]*color: var\(--aa-ui-warning\);/);
	assert.match(theme, /\.aa-prompt-selector-favorite\.is-active \{[^}]*background: transparent;[^}]*box-shadow: none;/);
	assert.match(theme, /\.aa-prompt-selector-favorite\.is-active \.aa-ui-icon \{ fill: currentColor; \}/);
});

test("workspace visual hierarchy uses a compact shell, dedicated icon and active page rail", () => {
	assert.match(workspace, /icon: "aaalice-workspace-sidebar-icon"/);
	assert.match(workspace, /element\.classList\.add\("aa-workspace-host"\)/);
	assert.match(theme, /\.aa-workspace-host \{[^}]*height: 100%;[^}]*min-height: 0;[^}]*overflow: hidden;/);
	assert.match(theme, /\.aa-workspace \{[^}]*flex: 1;/);
	assert.match(theme, /\.aaalice-workspace-sidebar-icon[\s\S]*mask: url\("\.\.\/assets\/aaalice-workspace\.svg"\)/);
	assert.match(workspaceIcon, /viewBox="0 0 24 24"/);
	assert.match(workspaceIcon, /stroke-linecap="round"/);
	assert.doesNotMatch(workspaceIcon, /<circle/);
	assert.match(components, /createPageRail/);
	assert.match(components, /aa-dashboard-page-cursor/);
	assert.match(components, /root\.update = update/);
	assert.match(components, /active\.offsetTop/);
	assert.match(components, /const items = new Map\(\)/);
	assert.doesNotMatch(components, /transitionFromId|\* 27|cursorOffset/);
	assert.match(workspace, /const dashboardPageRails = new WeakMap\(\)/);
	assert.match(workspace, /pageRail\.update\(\{/);
	assert.match(components, /requestAnimationFrame/);
	assert.match(components, /aria-current/);
	assert.match(components, /addEventListener\("wheel"/);
	assert.match(components, /passive: false/);
	assert.match(components, /ArrowUp/);
	assert.match(components, /PageDown/);
	assert.doesNotMatch(components, /aa-workspace-brand/);
	assert.match(components, /ariaLabel: title/);
	assert.match(components, /root\.dataset\.workspace = activeTab/);
	assert.match(components, /root\.dataset\.workspace = value/);
	assert.match(workspace, /className: "aa-dashboard-edit-toggle"/);
	assert.match(workspace, /variant: "ghost"/);
	assert.match(workspace, /active: editMode/);
	assert.match(theme, /\.aa-dashboard-edit-toggle\.aa-ui-button\.is-active/);
	assert.match(theme, /\.aa-workspace\[data-workspace="library"\] \{[^}]*--aa-ui-accent: var\(--aa-workspace-library-accent\)/);
	assert.match(theme, /--aa-ui-accent-soft: color-mix/);
	assert.match(theme, /--aa-ui-focus: var\(--aa-workspace-library-accent\)/);
	assert.match(theme, /\.aa-workspace-tabs\[data-value="library"\]/);
	assert.match(theme, /\.aa-workspace-tabs \{[^}]*display: grid;[^}]*overflow: hidden;/);
	assert.match(theme, /transform \.2s cubic-bezier/);
	assert.doesNotMatch(workspace.match(/function renderWorkspace[\s\S]*?\n}/)?.[0] || "", /scheduleRender/);
	assert.doesNotMatch(components, /aa-control-card-indicator/);
	assert.match(theme, /\.aa-dashboard-page-dot\.is-active/);
	assert.match(theme, /\.aa-dashboard-page-rail:hover \.aa-dashboard-page-dot/);
	assert.match(theme, /\.aa-dashboard-page-list/);
	assert.match(theme, /\.aa-dashboard-page-rail\.is-expanded/);
	assert.match(theme, /\.aa-dashboard-page-cursor/);
	assert.match(theme, /transform \.16s cubic-bezier/);
	assert.match(theme, /\.aa-dashboard-page-dot\.is-active/);
	assert.match(theme, /margin-right: auto/);
	assert.match(theme, /justify-content: space-between/);
	assert.match(theme, /backdrop-filter: blur\(12px\)/);
	assert.match(workspace, /initialEdge: detail\.source === "boundary" && direction === "backward" \? "bottom" : "top"/);
	assert.match(workspace, /aa-dashboard-scroll\$\{pageTransitionClass\}/);
	assert.match(dashboardInteractions, /export function bindDashboardBoundaryPaging/);
	assert.match(dashboardInteractions, /isEnabled = \(\) => true/);
	assert.match(dashboardInteractions, /event\.defaultPrevented/);
	assert.match(dashboardInteractions, /direction > 0 \? scroller\.scrollTop >= maxScrollTop - 1 : scroller\.scrollTop <= 1/);
	assert.match(workspace, /isEnabled: \(\) => !viewState\.searchOpen && !scroll\.querySelector\("\.aa-dashboard-grid-v2\.is-dragging"\)/);
	assert.match(workspace, /canAdvance: \(\) => activePageIndex >= 0/);
	assert.match(workspace, /canRetreat: \(\) => activePageIndex > 0/);
	assert.doesNotMatch(workspace, /canAdvance: \(\) => !editMode/);
	assert.match(workspace, /pageRail\.selectIndex\(activePageIndex \+ 1, \{ source: "boundary" \}\)/);
	assert.match(workspace, /pageRail\.selectIndex\(activePageIndex - 1, \{ source: "boundary" \}\)/);
	assert.match(components, /root\.selectIndex = \(index, options\) => selectIndex\(index, options\)/);
	assert.match(workspace, /captureDashboardPageSnapshot/);
	assert.match(workspace, /\.aa-dashboard-scroll:not\(\.is-page-leaving\)/);
	assert.match(workspace, /pageTransition\?\.initialEdge === "bottom"/);
	assert.match(workspace, /detail\.source === "boundary"\) pageRail\.showTemporarily\(1100\)/);
	assert.match(components, /root\.showTemporarily = \(duration = 1100\)/);
	assert.match(components, /temporaryExpansionTimer = setTimeout\(\(\) => \{[\s\S]*if \(!pointerHovered\) setExpanded\(false\)/);
	assert.match(workspace, /aa-dashboard-page-stage/);
	assert.match(theme, /\.aa-dashboard-page-stage \{[^}]*overflow: hidden;/);
	assert.match(theme, /@keyframes aa-dashboard-page-forward-in/);
	assert.match(theme, /@keyframes aa-dashboard-page-forward-out/);
	assert.match(theme, /@keyframes aa-dashboard-page-backward-in/);
	assert.match(theme, /@keyframes aa-dashboard-page-backward-out/);
	assert.match(theme, /\.aa-dashboard-scroll\.is-page-entering-forward/);
	assert.match(theme, /\.aa-dashboard-scroll\.is-page-leaving-forward/);
	assert.match(theme, /prefers-reduced-motion: reduce[\s\S]*\.aa-dashboard-scroll\.is-page-entering/);
});

test("PromptSelector exposes scannable selected and category states", () => {
	assert.match(selector, /aa-prompt-selector-toolbar/);
	assert.match(selector, /aa-prompt-selector-search-toggle/);
	assert.match(selector, /searchToggleButton\(\{ label:[^}]*value: query/);
	assert.match(selector, /iconName: "arrowRight"[^}]*className: "aa-ui-search-collapse"/);
	assert.match(selector, /aa-prompt-selector-search/);
	assert.match(selector, /search\.className = "aa-ui-search-input"/);
	assert.match(selector, /search\.setAttribute\("data-autocomplete-plus", ""\)/);
	assert.match(selector, /search\.hasAttribute\("data-autocomplete-plus-open"\)/);
	assert.match(selector, /queueMicrotask/);
	assert.match(selector, /list\._aaaliceVirtualList\?\.setItems\(filteredEntries\(node, stateFor\(node\)\), \{ preserveScroll: false \}\)/);
	assert.match(selector, /mountPromptEntries/);
	assert.match(selector, /mountVirtualList/);
	assert.match(selector, /root\.append\(toolbar, list, footer\);\s*list\.scrollTop = listScrollTop;\s*virtualList\.refresh\(\);/s);
	assert.match(selector, /createImagePreview/);
	assert.match(imagePreview, /aa-image-preview-selection/);
	assert.match(imagePreview, /icon\("statusCheck"\)/);
	assert.match(selector, /aa-prompt-selector-title/);
	assert.match(selector, /bindPromptEntryDetails\(copy, entry\)/);
	assert.match(promptEntryDetails, /promptDetailsTooltip = createTooltip/);
	assert.match(promptEntryDetails, /PROMPT_DETAILS_HOVER_DELAY = 600/);
	assert.match(selector, /selectionSummaryTooltip = createTooltip/);
	assert.match(selector, /bindSelectionSummary\(categoryFilter\.control/);
	assert.match(selector, /bindSelectionSummary\(summary/);
	assert.match(selector, /categorySelectionSummary/);
	assert.match(selector, /selectedPromptSummary/);
	assert.match(promptEntryDetails, /aa-prompt-entry-details-prompt/);
	assert.match(promptEntryDetails, /collectionItems\(entry\.collections/);
	assert.match(selector, /aa-prompt-selector-summary/);
	assert.match(selector, /aa-prompt-selector-count/);
	assert.match(selector, /_aaalicePromptSelectedOnly/);
	assert.match(selector, /"aria-pressed": String\(selectedOnly\)/);
	assert.match(selector, /entries\.filter\(\(entry\) => selectedIds\.has\(entry\.id\)\)/);
	assert.match(selector, /countPromptSelectionsByCategory/);
	assert.match(selector, /aa-prompt-selector-clear-action/);
	assert.match(selector, /state\.selections\.length \? button/);
	assert.match(selector, /mutate\(node, clearPromptSelections\)/);
	assert.match(selector, /aa-prompt-selector-empty/);
	assert.match(selector, /isSelected \? " is-selected"/);
	assert.match(selector, /className: "aa-prompt-selector", attrs: \{ "data-capture-wheel": "true" \}/);
	assert.match(selector, /className: "aa-prompt-selector-list", attrs: \{ tabindex: "0" \}/);
	assert.match(selector, /list\.addEventListener\("pointerenter", \(\) => \{[\s\S]*root\.contains\(active\)[\s\S]*active\.matches\('input, textarea, select, \[contenteditable="true"\]'\)[\s\S]*list\.focus\(\{ preventScroll: true \}\)/);
	assert.doesNotMatch(selector, /list\.addEventListener\("wheel"/);
	assert.match(theme, /grid-template-columns: repeat\(2, minmax\(0, 1fr\)\) 34px 34px/);
	assert.match(theme, /\.aa-prompt-selector-toolbar\.is-searching \{ grid-template-columns: minmax\(0, 1fr\); \}/);
	assert.match(theme, /\.dom-widget:has\(> \.aa-prompt-selector\) \{[^}]*position: relative;[^}]*min-height: 240px;[^}]*overflow: hidden;[^}]*pointer-events: none !important;/);
	assert.match(theme, /\.aa-prompt-selector \{[^}]*position: absolute;[^}]*inset: 0;[^}]*min-height: 0;[^}]*overflow: hidden;/);
	assert.match(theme, /\.lg-node-widgets \.aa-prompt-selector \{[^}]*position: relative;[^}]*inset: auto;[^}]*height: 100%;[^}]*min-height: 240px;/);
	assert.match(theme, /\.aa-prompt-selector-list \{[^}]*min-height: 0;[^}]*overflow: auto;/);
	assert.match(theme, /\.aa-prompt-selector\.is-resizing, \.aa-prompt-selector\.is-resizing \* \{ pointer-events: none !important; \}/);
	assert.match(theme, /\.aa-prompt-selector-row\.is-selected/);
	assert.match(theme, /\.aa-prompt-selector-row \{[^}]*grid-template-columns: 38px minmax\(0, 1fr\);/);
	assert.match(theme, /\.aa-prompt-selector-row-actions \{[^}]*position: absolute;/);
	assert.match(theme, /--aa-prompt-row-surface: var\(--aa-ui-accent-soft\)/);
	assert.match(theme, /linear-gradient\(90deg, transparent, var\(--aa-prompt-row-surface\) 28%\)/);
	assert.doesNotMatch(theme, /aa-prompt-selector-row-actions \{ background:[^}]*aa-ui-surface/);
	assert.match(theme, /\.aa-prompt-selector-row:has\(\.aa-prompt-selector-favorite\.is-active\) \.aa-prompt-selector-copy \{ padding-right: 62px; \}/);
	assert.match(theme, /\.aa-prompt-selector-row\.is-selected:hover \.aa-prompt-selector-copy/);
	assert.match(theme, /\.aa-prompt-selector-weight \{[^}]*cursor: ns-resize;/);
	assert.match(theme, /\.aa-prompt-selector-summary\.is-active/);
	assert.match(uiStyles, /\.aa-image-preview-selectable:has\(input:checked\)/);
	assert.match(uiStyles, /\.aa-image-preview-selectable \.aa-image-preview-selection\s*\{[^}]*background:\s*color-mix\(in srgb, var\(--aa-ui-accent\) 18%, transparent\)/s);
	assert.match(uiStyles, /\.aa-image-preview-selectable \.aa-image-preview-selection > \.aa-ui-icon\s*\{[^}]*border:\s*0;[^}]*background:\s*transparent;[^}]*color:\s*var\(--aa-ui-on-media\);[^}]*stroke-width:\s*2\.5/s);
	assert.match(uiStyles, /\.aa-image-preview-selectable:has\(input:checked\) \.aa-image-preview-media > img\s*\{[^}]*filter:\s*saturate\(\.92\) brightness\(\.9\)/s);
	assert.match(theme, /\.aa-prompt-entry-details-tooltip/);
	assert.match(theme, /\.aa-prompt-selection-tooltip/);
	assert.match(theme, /\.aa-prompt-selection-summary > ol/);
	assert.match(uiStyles, /\.aa-ui-tooltip\s*\{[^}]*pointer-events:\s*none/s);
	assert.doesNotMatch(theme.match(/\.aa-image-preview-tooltip\s*\{[^}]*\}/s)?.[0] || "", /pointer-events/);
	assert.doesNotMatch(theme.match(/\.aa-prompt-entry-details-tooltip\s*\{[^}]*\}/s)?.[0] || "", /pointer-events/);
	assert.doesNotMatch(promptEntryDetails, /aa-prompt-entry-details-tooltip[^\n]*interactive:\s*true/);
	assert.match(theme, /\.aa-prompt-entry-details-prompt > p, \.aa-prompt-entry-details-note > p\s*\{[^}]*white-space:\s*pre-wrap/s);
});

test("PromptSelector uses the spacious reference size as its default and resize floor", () => {
	assert.match(selector, /const DEFAULT_SIZE = \[440, 560\]/);
	assert.match(selector, /const MIN_WIDTH = 440/);
	assert.match(selector, /const MIN_HEIGHT = 560/);
	assert.match(selector, /const MIN_WIDGET_HEIGHT = 240/);
	assert.match(selector, /getMinHeight: \(\) => MIN_WIDGET_HEIGHT/);
	assert.match(selector, /if \(!loaded\) node\.setSize\?\.\(DEFAULT_SIZE\)/);
	assert.match(selector, /Math\.max\(MIN_WIDTH, size\[0\]\)/);
	assert.match(selector, /Math\.max\(MIN_HEIGHT, size\[1\]\)/);
	assert.match(theme, /\.lg-node:has\(\.aa-prompt-selector\):not\(\[data-collapsed\]\) > \[data-testid="node-inner-wrapper"\] \{[^}]*min-width: 440px;[^}]*min-height: 590px;/);
	assert.doesNotMatch(theme, /\.lg-node:has\(\.aa-prompt-selector\):not\(\[data-collapsed\]\) \{[^}]*min-width:/);
});

test("filter dropdowns reuse the shared animated select control", () => {
	assert.match(ui, /export function selectControl/);
	assert.match(ui, /aria-expanded/);
	assert.match(ui, /icon\("moveDown"/);
	assert.match(selector, /promptFilterSelect/);
	assert.match(selector, /selectControl\(\{/);
	assert.match(workspace, /className: "aa-library-filter-select"/);
	assert.match(uiStyles, /\.aa-ui-select\.is-open \.aa-ui-select__arrow/);
	assert.match(uiStyles, /padding-right: 38px/);
	assert.match(ui, /syncOptionColor/);
	assert.match(ui, /--aa-ui-select-option-color/);
	assert.match(categoryColor, /export function categorySelectOption/);
	assert.match(selector, /value: option\.id, color: option\.color/);
	assert.match(workspace, /categories\.map\(categorySelectOption\)/);
});

test("workspace empty states and compact action bars keep narrow sidebars deliberate", () => {
	assert.match(components, /aa-dashboard-page-rail/);
	assert.match(workspace, /aa-dashboard-toolbar/);
	assert.match(workspace, /aa-library-toolbar/);
	assert.match(workspace, /iconName: "upload", label: t\("aaalice\.workspace\.preset\.export"/);
	assert.match(workspace, /iconName: "download", label: t\("aaalice\.workspace\.preset\.import"/);
	assert.match(workspace, /iconName: "upload", label: selected\.size[\s\S]*libraryUi\.export/);
	assert.match(workspace, /iconName: "download", label: t\("aaalice\.workspace\.libraryUi\.import"/);
	assert.match(workspace, /aa-workspace-empty aa-dashboard-empty/);
	assert.match(workspace, /className: "aa-dashboard-page-empty"/);
	assert.match(workspace, /aa-workspace-empty aa-library-empty/);
	assert.match(theme, /\.aa-dashboard-page-rail\.is-empty \{ display: none; \}/);
	assert.match(theme, /\.aa-dashboard-page-rail \{[^}]*right: -10px;[^}]*width: 34px;[^}]*padding-right: 10px;/);
	assert.match(theme, /\.aa-workspace-empty\[hidden\] \{ display: none; \}/);
	assert.match(theme, /\.aa-dashboard-page-empty \{[^}]*position: absolute;[^}]*inset: 0;[^}]*place-content: center;[^}]*text-align: center;/);
	assert.match(theme, /\.aa-library-filters \{ display: grid; grid-template-columns: minmax\(0, 1fr\) minmax\(0, 1fr\);/);
});

test("dashboard toolbar identifies the current page in its available space", () => {
	assert.match(workspace, /className: `aa-dashboard-page-name\$\{pageTransitionClass\}`[^\n]+role: "heading"[^\n]+"aria-current": "page"/);
	assert.match(theme, /\.aa-dashboard-page-name \{[^}]*min-width: 0;[^}]*flex: 1;/);
	assert.match(theme, /\.aa-dashboard-page-name \{[^}]*border-left: 2px solid var\(--aa-ui-accent\);[^}]*font-size: 13px;[^}]*font-weight: 700;/);
	assert.match(theme, /\.aa-dashboard-page-name > span \{[^}]*text-overflow: ellipsis;/);
});

test("detached context menus retain theme tokens and visible hover feedback", () => {
	assert.match(uiStyles, /\.aa-ui-popover,\s*\n\.aa-ui-context-menu,\s*\n\.aa-ui-tooltip/);
	assert.match(uiStyles, /\.aa-ui-context-menu__item\.aa-ui-button:hover:not\(:disabled\)[^}]*border-color: transparent;[^}]*background: color-mix\(in srgb, var\(--aa-ui-accent\) 14%, var\(--aa-ui-control\)\)[^}]*box-shadow: none/);
});

test("layout editing keeps creation and layout tools in the primary toolbar", () => {
	assert.match(workspace, /className: "aa-dashboard-add-page"/);
	assert.match(workspace, /className: "aa-dashboard-add-separator"/);
	assert.match(workspace, /className: "aa-dashboard-tidy-layout"/);
	assert.match(workspace, /className: "aa-dashboard-page-menu"/);
	assert.match(workspace, /editMode \? \[[\s\S]*aa-dashboard-add-page[\s\S]*aa-dashboard-add-separator[\s\S]*aa-dashboard-tidy-layout[\s\S]*\] : \[[\s\S]*preset\.export[\s\S]*preset\.import[\s\S]*search\.toggle/);
	assert.doesNotMatch(workspace, /if \(editMode\) container\.append\(createWorkspaceToolbar/);
	assert.doesNotMatch(components, /aa-dashboard-page-add|onAdd/);
	assert.doesNotMatch(theme, /aa-dashboard-page-add/);
	assert.match(theme, /\.is-layout-editing \.aa-dashboard-toolbar > \.aa-ui-button \{[^}]*height: 29px;[^}]*min-height: 29px;[^}]*border-radius: 7px;/);
	assert.match(theme, /\.is-layout-editing \.aa-dashboard-toolbar > :is\(\.aa-dashboard-add-separator, \.aa-dashboard-tidy-layout, \.aa-dashboard-page-menu\)/);
});

test("Dashboard V2 replaces mandatory sections with optional grid groups", () => {
	assert.match(workspace, /createGroup\(current, page\.id/);
	assert.match(providers, /sourceGroup: \{ source: \{ provider: this\.id, hostId \}/);
	assert.match(workspace, /function sharedSourceGroup\(controls\)/);
	assert.match(workspace, /addItems\(current, page\.id, chosen, \{ sourceGroup: sharedSourceGroup\(chosen\) \}\)/);
	assert.match(dashboardCommands, /function findSourceGroup/);
	assert.match(dashboardCommands, /ungroupedSourceItems/);
	assert.match(dashboardCommands, /createGroup\(next, pageId, ungroupedSourceItems\.map/);
	assert.match(dashboardComponents, /export function createDashboardGroup/);
	assert.match(dashboardComponents, /aa-dashboard-composite-card/);
	assert.match(dashboardComponents, /classList\.add\("is-group-member"\)/);
	assert.match(dashboardComponents, /dataset\.dashboardGroupMember/);
	assert.match(dashboardComponents, /data-dashboard-group-id/);
	assert.match(dashboardComponents, /page\.items\.filter\(\(item\) => !item\.groupId\)/);
	assert.match(dashboardLayout, /export function firstAvailableLayout/);
	assert.match(dashboardCommands, /export function deleteGroup/);
	assert.doesNotMatch(workspace, /createSection|findSection|lastSectionId|\.sections/);
	assert.doesNotMatch(components, /createSectionCard/);
	assert.doesNotMatch(theme, /aa-dashboard-section/);
	assert.match(theme, /\.aa-dashboard-group \.aa-control-card\.is-group-member \{[^}]*border:\s*0;[^}]*background:\s*color-mix/);
	assert.doesNotMatch(theme, /\.aa-dashboard-group \.aa-control-card\.is-group-member \{[^}]*var\(--aa-dashboard-control-tone\)/);
	assert.match(theme, /\.is-layout-editing \.aa-dashboard-group \.aa-control-card\.is-group-member:is\(\.is-selected, \.is-drop-target\)/);
});

test("Dashboard footprints are stable model hints rather than DOM measurements", () => {
	assert.match(providers, /rowSpan: recommendedControlRowSpan/);
	assert.match(dashboardSizing, /export function dashboardCardHeight/);
	assert.match(dashboardSizing, /export function recommendedControlRowSpan/);
	assert.match(dashboardSizing, /export function recommendedGroupRowSpan/);
	assert.doesNotMatch(dashboardSizing, /document|getComputedStyle|ResizeObserver/);
	assert.match(dashboardLayout, /layout\.row \+ layout\.rowSpan/);
});

test("dashboard cards expose equal visual gutters without changing fine row geometry", () => {
	assert.match(theme, /--aa-dashboard-card-gap:\s*6px/);
	assert.match(theme, /--aa-dashboard-track-gap:\s*2px/);
	assert.match(theme, /grid-auto-rows:\s*4px/);
	assert.match(theme, /column-gap:\s*var\(--aa-dashboard-card-gap\)/);
	assert.match(theme, /row-gap:\s*var\(--aa-dashboard-track-gap\)/);
	assert.match(theme, /height:\s*calc\(100% - var\(--aa-dashboard-card-gap\) \+ var\(--aa-dashboard-track-gap\)\)/);
	assert.doesNotMatch(theme, /margin-bottom:\s*calc\(var\(--aa-dashboard-card-gap\) - var\(--aa-dashboard-track-gap\)\)/);
});

test("dashboard control contents stay within their declared grid footprints", () => {
	assert.match(theme, /\.aa-control-card-header \{[^}]*min-height:\s*14px;[^}]*line-height:\s*14px;/);
	assert.match(theme, /\.aa-control-card-title \{[^}]*font-size:\s*12px;[^}]*font-weight:\s*650;/);
	assert.match(theme, /\.aa-control-card-title::before \{[^}]*background: var\(--aa-control-kind-tone, transparent\)/);
	assert.match(theme, /\.aa-control-card\[data-control-kind="numeric"\] \{ --aa-control-kind-tone/);
	assert.match(theme, /\.aa-control-card\[data-control-kind="boolean"\] \{ --aa-control-kind-tone/);
	assert.match(theme, /\.aa-workspace-control-input \{[^}]*opacity: \.62;/);
	assert.match(theme, /\.aa-control-card:focus-within \.aa-workspace-control-input[^}]*\{ opacity: 1; \}/);
	assert.match(theme, /:has\(\.aa-control-card:hover\) \.aa-control-card:not\(:hover\):not\(:focus-within\) \.aa-workspace-control-input \{ opacity: \.45; \}/);
	assert.match(theme, /\.aa-control-card\[data-control-kind="image"\] \.aa-workspace-control-input[^}]*\{ opacity: 1; \}/);
	assert.match(theme, /\.aa-control-choice-select \.aa-ui-select__native \{[^}]*height:\s*32px;[^}]*min-height:\s*32px;/);
	assert.match(theme, /data-control-kind="taglist"[^}]*aa-taglist-control[^}]*height:\s*32px;[^}]*min-height:\s*32px;/);
	assert.match(workspaceControls, /control\.dataset\.headerOnly = "true"; control\.headerAccessories = \[accessory\];/);
	assert.match(theme, /\.aa-dashboard-group \{[^}]*padding:\s*5px;/);
	assert.match(theme, /\.aa-dashboard-group-header \{[^}]*min-height:\s*26px;/);
	assert.match(dashboardComponents, /aa-dashboard-group-count/);
	assert.match(dashboardComponents, /icon\("drag", \{ className: "aa-dashboard-group-grip" \}\)/);
	assert.match(theme, /\.aa-dashboard-group-count \{[^}]*border-radius: 999px;/);
	assert.match(theme, /\.aa-dashboard-group-marker \{[^}]*linear-gradient/);
	assert.match(theme, /\.aa-dashboard-group:hover \{[^}]*translateY\(-1px\)/);
	assert.match(theme, /\.is-layout-editing \.aa-dashboard-group:hover \{ transform: none; \}/);
	assert.match(theme, /\.aa-control-numeric-value\.is-committed \{ animation: aa-control-commit-flash/);
	assert.match(numericControl, /classList\.add\("is-committed"\)/);
	assert.match(numericControl, /requestAnimationFrame\(\(\) => \{/);
	assert.match(numericControl, /if \(valueButton\.isConnected\) return;/);
});

test("Dashboard V2 layout editing uses transient pointer gestures and one command commit", () => {
	assert.match(dashboardInteractions, /pointerdown/);
	assert.match(dashboardInteractions, /setPointerCapture/);
	assert.match(dashboardInteractions, /translate3d/);
	assert.match(dashboardInteractions, /function gridTargetAt/);
	assert.match(dashboardInteractions, /target\.column = Math\.max\(0, Math\.min\(columns - columnSpan, target\.column\)\)/);
	assert.match(dashboardInteractions, /aa-dashboard-drop-preview/);
	assert.match(dashboardInteractions, /style\.gridAutoRows/);
	assert.match(dashboardInteractions, /--aa-dashboard-row-span/);
	assert.match(dashboardInteractions, /export function grabSpanOffset/);
	assert.match(dashboardInteractions, /grabColumnOffset = grabSpanOffset/);
	assert.match(dashboardInteractions, /grabRowOffset/);
	assert.match(dashboardInteractions, /rawTarget\.column - gesture\.grabColumnOffset/);
	assert.match(dashboardInteractions, /rawTarget\.row - gesture\.grabRowOffset/);
	assert.match(dashboardInteractions, /event\.key === "Escape"/);
	assert.match(dashboardInteractions, /onDropItems/);
	assert.doesNotMatch(dashboardInteractions, /graph\.extra|beforeChange|afterChange/);
	assert.match(workspace, /onDropItems: \(ids, target\) => updateDashboard/);
	assert.match(dashboardInteractions, /kind: "marquee"/);
	assert.match(dashboardInteractions, /aa-dashboard-marquee/);
	assert.match(dashboardInteractions, /intersectingSelectionIds/);
	assert.match(dashboardInteractions, /unbind\.setSelection/);
	assert.match(dashboardSelection, /export function selectionRectangle/);
	assert.match(components, /export function createSelectionActionBar/);
	assert.match(workspace, /createSelectionActionBar\(/);
	assert.match(workspace, /aaalice\.workspace\.selection\.group/);
	assert.match(theme, /\.aa-dashboard-selection-bar/);
	assert.match(workspace, /body\.classList\.toggle\("has-selection-actions", count > 0\)/);
	assert.match(theme, /\.aa-dashboard-body\.has-selection-actions \.aa-dashboard-scroll \{ padding-bottom: 72px; \}/);
	assert.doesNotMatch(theme, /\.is-layout-editing \.aa-dashboard-scroll \{ padding-bottom: 72px; \}/);
	assert.match(theme, /\.aa-dashboard-scroll \{[^}]*display: flex;[^}]*flex-direction: column;/);
	assert.match(theme, /\.aa-dashboard-grid-v2 \{[^}]*flex: 1;/);
	assert.match(theme, /\.aa-dashboard-grid-v2\.is-editing \{[^}]*min-height: 100%;/);
	assert.match(workspace, /aa-dashboard-separator-label/);
	assert.match(workspace, /role: "separator"/);
	assert.match(theme, /\.aa-dashboard-separator::before,[\s\S]*\.aa-dashboard-separator::after/);
	assert.match(theme, /\.aa-dashboard-separator-label \{[^}]*text-align: center;/);
	assert.match(theme, /grid-row: var\(--aa-dashboard-row\) \/ span var\(--aa-dashboard-row-span\)/);
	assert.match(dashboardSizing, /DASHBOARD_GRID_COLUMNS = 12/);
	assert.match(dashboardSizing, /DASHBOARD_MIN_CONTROL_COLUMN_SPAN = 3/);
	assert.match(components, /data-dashboard-resize-handle/);
	assert.match(dashboardInteractions, /kind: "resize"/);
	assert.match(dashboardInteractions, /gesture\.preview\.dataset\.dropRow = gesture\.element\.dataset\.dropRow/);
	assert.match(dashboardInteractions, /gesture\.preview\.dataset\.dropColumn = gesture\.element\.dataset\.dropColumn/);
	assert.match(dashboardInteractions, /Math\.round\(dx/);
	assert.match(dashboardInteractions, /Math\.round\(dy/);
	assert.match(dashboardInteractions, /onResizeItem\?\./);
	assert.match(workspace, /onResizeItem: \(itemId, size\) => updateDashboard/);
	assert.match(theme, /\.aa-dashboard-resize-handle/);
	assert.match(theme, /cursor: nwse-resize/);
});

test("workspace list selection reuses the shared checkbox control", () => {
	assert.match(components, /checkboxControl\(\{/);
	assert.match(components, /root\.selectionControl = checkbox/);
	assert.match(ui, /export function checkboxControl/);
	assert.match(uiStyles, /\.aa-ui-checkbox\.is-checked/);
	assert.doesNotMatch(uiStyles, /\.aa-ui-dialog input\[type="checkbox"\]/);
});

test("add-controls dialog uses a compact structured picker", () => {
	assert.match(workspace, /aa-add-controls-target-grid/);
	assert.match(workspace, /aa-add-controls-section aa-add-controls-picker/);
	assert.match(workspace, /aa-add-controls-selection-count/);
	assert.match(workspace, /const pageSelect = selectControl/);
	assert.doesNotMatch(workspace, /sectionSelect|target\.section|newSection/);
	assert.match(workspace, /aa-add-controls-select-all/);
	assert.match(workspace, /binding\.selectAll/);
	assert.doesNotMatch(workspace, /aa-add-controls-footer-count/);
	assert.match(workspace, /selected = new Set\(controls.*!existing\.has/);
	assert.match(workspace, /binding\.addSelected/);
	assert.match(workspace, /\.\.\.\(duplicateKeys\.size \? \[duplicateSetting\] : \[\]\)/);
	assert.match(workspace, /confirmButton\.disabled = selected\.size === 0/);
	assert.match(workspace, /size: "md", className: "aa-add-controls-dialog-shell"/);
	assert.match(theme, /\.aa-add-controls-list \{ display: grid;/);
	assert.match(theme, /grid-template-columns: repeat\(2, minmax\(0, 1fr\)\)/);
});

test("adding controls reminds the user to save the workflow", () => {
	assert.match(workspace, /function remindWorkflowSave\(detail\)/);
	assert.match(workspace, /severity: "warn"/);
	assert.match(workspace, /aaalice\.workspace\.binding\.saveWorkflowReminder/);
	assert.match(enLocale, /Save the workflow to keep these sidebar controls/);
	assert.match(zhLocale, /请保存工作流以保留这些侧边栏参数/);
});

test("complete sidebar presets track layout and values as a custom working copy", () => {
	assert.match(workspace, /const DASHBOARD_PRESETS_EXTRA_KEY = "aaaliceSidebarPresets"/);
	assert.match(workspace, /graphSyncSignature[\s\S]*DASHBOARD_PRESETS_EXTRA_KEY/);
	assert.match(workspace, /delete extra\[LEGACY_VALUE_PRESETS_EXTRA_KEY\]/);
	assert.match(workspace, /createDashboardPresetPicker\(\{/);
	assert.doesNotMatch(workspace, /!editMode \? createDashboardPresetPicker/);
	assert.match(workspace, /currentDashboardPresetSnapshot/);
	assert.match(workspace, /confirmDashboardPresetSwitch/);
	assert.match(workspace, /planDashboardPresetApplication/);
	assert.match(workspace, /applyDashboardSnapshotPlan/);
	assert.match(workspace, /dashboardPreset\.saveWorkflowReminder/);
	assert.match(workspace, /deleteCurrentDashboardPreset[\s\S]*confirmAction\(message, \{ title: dashboardPresetLabels\(\)\.delete, confirmLabel: dashboardPresetLabels\(\)\.delete, danger: true \}\)[\s\S]*removeDashboardPreset/);
	assert.match(components, /export function createDashboardPresetPicker/);
	assert.match(components, /error = null/);
	assert.match(components, /aa-value-preset-empty is-error/);
	assert.match(workspace, /error: dashboardPresetModelError/);
	assert.match(components, /selected \? `\$\{selected\.name\}\$\{modified \? "\*" : ""\}` : labels\.placeholder/);
	assert.match(workspace, /placeholder: t\("aaalice\.workspace\.dashboardPreset\.placeholder", "Select preset"\)/);
	assert.match(enLocale, /"placeholder": "Select preset"/);
	assert.match(zhLocale, /"placeholder": "选择预设"/);
	assert.doesNotMatch(components, /is-unsaved|labels\.unsaved/);
	assert.match(components, /selected\.name/);
	assert.match(components, /selected\.name\}\$\{modified \? "\*" : ""\}/);
	assert.match(components, /comparison\?\.layoutChanges/);
	assert.match(components, /comparison\?\.valueChanges/);
	assert.match(components, /aria-haspopup": "dialog"/);
	assert.match(components, /aa-value-preset-current-primary/);
	assert.match(components, /aa-value-preset-option-actions/);
	assert.match(components, /className: "aa-value-preset-popover", width: 340/);
	assert.match(components, /labels\.presetCount/);
	assert.doesNotMatch(components, /createContextMenu/);
	assert.match(components, /button\(\{ label: labels\.add[\s\S]*iconName: "add"/);
	assert.doesNotMatch(components, /labels\.description/);
	assert.doesNotMatch(components, /aa-value-preset-popover__footer/);
	assert.match(components, /role: "toolbar", "aria-label": labels\.manage/);
	assert.match(components, /iconName: "edit", label: labels\.rename[\s\S]*iconName: "copy", label: labels\.duplicate[\s\S]*iconName: "delete", label: labels\.delete/);
	assert.match(components, /labels\.modified/);
	assert.match(components, /labels\.saveCurrent/);
	assert.doesNotMatch(components, /labels\.saveAs/);
	assert.match(components, /className: `aa-value-preset-list\$\{availablePresets\.length \? "" : " is-empty"\}`/);
	assert.match(components, /aa-value-preset-empty__icon/);
	assert.match(components, /children: \[icon\("layout"\)\]/);
	assert.match(components, /dirty && availablePresets\.length/);
	assert.match(components, /labels\.emptyAction/);
	assert.doesNotMatch(components, /aa-value-preset-trigger__eyebrow/);
	assert.match(theme, /\.aa-value-preset-trigger \{[^}]*display: flex;[^}]*height: 29px;[^}]*align-items: center;/);
	assert.match(theme, /\.aa-value-preset-trigger__name \{[^}]*flex: 1;[^}]*text-overflow: ellipsis;/);
	assert.match(theme, /\.aa-value-preset-trigger\.is-modified \{/);
	assert.doesNotMatch(theme, /is-unsaved/);
	assert.match(theme, /\.aa-value-preset-trigger\.is-modified \.aa-value-preset-trigger__name \{ font-style: italic; \}/);
	assert.match(theme, /\.aa-value-preset-popover\.aa-ui-popover/);
	assert.match(theme, /\.aa-value-preset-option-row:hover \.aa-value-preset-option-actions, \.aa-value-preset-option-row:focus-within \.aa-value-preset-option-actions/);
	assert.match(theme, /\.aa-value-preset-option-actions \.aa-ui-button\.is-danger:hover/);
	assert.match(theme, /\.aa-value-preset-list\.is-empty/);
	assert.match(theme, /\.aa-value-preset-empty__icon/);
	assert.match(theme, /\.aa-value-preset-switch-warning/);
	assert.match(dashboardPresets, /DASHBOARD_PRESETS_VERSION = 1/);
	assert.match(dashboardPresets, /export function compareDashboardPreset/);
	assert.match(dashboardPresets, /export function serializeDashboardPreset/);
	assert.match(dashboardPresetRuntime, /function uniqueBindings/);
	assert.match(dashboardPresetRuntime, /rollbackErrors/);
	assert.match(dashboardPresetRuntime, /export function applyDashboardSnapshotPlan/);
	assert.match(providers, /hasCustomPresetCodec/);
	assert.match(widgetAdapters, /readPresetValue/);
	assert.match(widgetAdapters, /validatePresetValue/);
	assert.match(widgetAdapters, /applyPresetValue/);
	assert.match(enLocale, /"title": "Sidebar presets"/);
	assert.match(zhLocale, /"title": "侧边栏预设"/);
	assert.match(enLocale, /"preset": \{ "title": "Layout backup"/);
	assert.match(zhLocale, /"preset": \{ "title": "布局备份"/);
});

test("library rows keep a stable thumbnail column and distinguish entry actions", () => {
	assert.match(workspace, /createSelectableImagePreview/);
	assert.match(workspace, /aa-library-entry-preview/);
	assert.doesNotMatch(workspace, /checkbox\.type = "checkbox"/);
	assert.match(workspace, /mountVirtualList/);
	assert.match(workspace, /closeImagePreview/);
	assert.match(workspace, /className: "aa-library-entry-edit"/);
	assert.match(workspace, /className: "aa-library-entry-delete"/);
	assert.match(workspace, /el\("label", \{ className: "aa-library-entry-copy"/);
	assert.match(workspace, /for: `aa-library-entry-\$\{entry\.id\}`/);
	assert.match(workspace, /preview\.input\.click\(\)/);
	assert.match(workspace, /bindPromptEntryDetails\(copy, entry\)/);
	assert.match(workspace, /closePromptEntryDetails\(\)/);
	assert.match(theme, /\.aa-library-entry \{[^}]*grid-template-columns: 48px minmax\(0, 1fr\) auto/);
	assert.match(theme, /\.aa-library-entry\.is-selected/);
	assert.match(uiStyles, /\.aa-image-preview-selectable:has\(input:checked\) \.aa-image-preview-selection/);
	assert.match(theme, /\.aa-library-entry-copy \{[^}]*justify-content: center/);
	assert.match(theme, /\.aa-library-entry-edit:hover/);
	assert.match(theme, /\.aa-library-entry-delete:hover/);
	assert.match(theme, /\.aa-image-preview-large/);
	assert.match(theme, /\.aa-image-preview-large > img\s*\{[^}]*width:\s*auto[^}]*max-height:/s);
	assert.match(theme, /\.aa-image-preview-caption\s*\{[^}]*position:\s*absolute[^}]*background:\s*color-mix\([^}]*transparent\)/s);
	assert.match(theme, /\.aa-image-preview-caption > small/);
	assert.match(imagePreview, /IMAGE_PREVIEW_HOVER_DELAY = 600/);
	assert.match(imagePreview, /addEventListener\("load", previewTooltip\.reposition/);
});

test("library selection actions operate on model data instead of rendered rows", () => {
	assert.doesNotMatch(workspace, /openBatchEdit|libraryUi\.batch|Edit selected entries/);
	assert.match(workspace, /className: "aa-library-selection-toggle"/);
	assert.match(workspace, /for \(const entry of visibleEntries\) selected\.add\(entry\.id\)/);
	assert.match(workspace, /if \(clearsSelection\) selected\.clear\(\)/);
	assert.match(workspace, /visibleEntries\.every\(\(entry\) => selected\.has\(entry\.id\)\)/);
	assert.match(workspace, /selectionToggle\.replaceChildren\(icon\(clearsSelection \? "close" : "statusCheck"\)/);
	assert.match(workspace, /selectionToggle\.classList\.toggle\("is-clear", clearsSelection\)/);
	assert.doesNotMatch(workspace, /querySelectorAll\([^\n]*aa-library-entry/);
	assert.match(theme, /\.aa-library-selection-actions/);
	assert.match(theme, /\.aa-library-selection-toggle\.is-clear:hover:not\(:disabled\)/);
	assert.match(workspace, /function openMoveSelected\(selected\)/);
	assert.match(workspace, /const entryIds = \[\.\.\.selected\]/);
	assert.match(workspace, /batchEntries\(\{ entryIds, categoryId: target\.value === "__none__" \? null : target\.value \}\)/);
	assert.match(workspace, /className: "aa-library-move-selected"/);
	assert.match(workspace, /moveSelected\.disabled = selected\.size === 0/);
	assert.match(theme, /\.aa-library-move-selected:hover:not\(:disabled\)/);
	assert.match(workspace, /className: "aa-library-export-selected"/);
	assert.match(workspace, /openLibraryExport\(\{ selected, categoryId, collectionId \}\)/);
	assert.match(workspace, /className: "aa-library-delete-selected"/);
	assert.match(workspace, /promptLibraryStore\.deleteEntries\(entryIds\)/);
	assert.match(workspace, /danger: true/);
	assert.match(theme, /\.aa-library-delete-selected:hover:not\(:disabled\)/);
});

test("prompt entry editor prioritizes prompt content and uses shared themed controls", () => {
	assert.match(workspace, /className: "aa-library-entry-dialog"/);
	assert.match(workspace, /size: "md"/);
	assert.match(workspace, /className: "aa-library-entry-section is-content"/);
	assert.match(workspace, /className: "aa-library-entry-lower"/);
	assert.match(workspace, /listboxControl\(\{/);
	assert.match(workspace, /multiSelectControl\(\{/);
	assert.match(workspace, /collectionIds: collections\.values\(\)/);
	assert.match(workspace, /className: "aa-library-entry-preview-card"/);
	assert.match(workspace, /previewFooter\.hidden = !\(file \|\| existingPreviewUrl\)/);
	assert.doesNotMatch(workspace, /libraryUi\.noPreview/);
	assert.match(workspace, /className: "aa-library-entry-preview-overlay"/);
	assert.match(workspace, /removePreviewRequested/);
	assert.match(workspace, /URL\.revokeObjectURL\(selectedPreviewUrl\)/);
	assert.match(ui, /export function listboxControl/);
	assert.match(ui, /const leadingIcon = el\("span", "aa-ui-listbox-select__leading-icon"\)/);
	assert.match(ui, /root\.classList\.toggle\("has-option-icon", Boolean\(iconName\)\)/);
	assert.match(ui, /\$\{optionIcon \? " has-icon" : ""\}/);
	assert.match(ui, /role: "listbox"/);
	assert.match(ui, /role: "option"/);
	assert.match(ui, /export function multiSelectControl/);
	assert.match(ui, /role: "group"/);
	assert.match(ui, /setAttribute\("aria-pressed", String\(active\)\)/);
	assert.match(uiStyles, /\.aa-ui-multiselect__option\.is-selected/);
	assert.match(uiStyles, /\.aa-ui-listbox__option\.is-selected/);
	assert.match(uiStyles, /\.aa-ui-listbox-select\.has-option-icon \.aa-ui-listbox-select__trigger/);
	assert.match(uiStyles, /\.aa-ui-listbox__option\.has-icon/);
	assert.match(theme, /\.aa-library-entry-dialog \{ width: min\(820px/);
	assert.match(theme, /\.aa-library-entry-dialog \.aa-library-entry-prompt-field textarea \{ min-height: 238px/);
	assert.match(theme, /\.aa-library-entry-dialog \.aa-library-entry-note-field \{[^}]*flex: 1;/);
	assert.match(theme, /\.aa-library-entry-dialog \.aa-library-entry-note-field textarea \{[^}]*flex: 1;/);
	assert.match(theme, /\.aa-library-entry-preview-footer\[hidden\] \{ display: none; \}/);
	assert.match(theme, /@media \(max-width: 720px\)[\s\S]*\.aa-library-entry-lower \{ grid-template-columns: 1fr;/);
});

test("taxonomy management is a complete single-dialog workspace", () => {
	assert.match(workspace, /function openTaxonomyManager/);
	assert.doesNotMatch(workspace, /function openTaxonomyChooser|function manageTaxonomy/);
	assert.match(workspace, /segmentedControl\(\{/);
	assert.match(workspace, /aa-taxonomy-list/);
	assert.match(workspace, /editingId === item\.id/);
	assert.match(workspace, /aa-taxonomy-footer/);
	assert.match(workspace, /usageCount\(item\)/);
	assert.match(theme, /\.aa-taxonomy-dialog/);
	assert.match(theme, /\.aa-taxonomy-tabs \{[^}]*margin-inline: auto/);
	assert.match(theme, /\.aa-taxonomy-tabs\[data-value="collections"\]/);
	assert.match(theme, /--aa-taxonomy-tab-color/);
	assert.match(theme, /\.aa-taxonomy-row\.is-editing/);
	assert.match(workspace, /colorInput\.type = "color"/);
	assert.match(workspace, /updateCategory\(item\.id, \{ name, color: colorInput\.value \}\)/);
	assert.match(workspace, /aa-taxonomy-color-swatch/);
	assert.match(components, /leading = null/);
	assert.match(categoryColor, /export function applyCategoryColor/);
	assert.match(theme, /\.aa-taxonomy-color-swatch/);
	assert.match(theme, /\.is-category-colored/);
	assert.match(workspace, /className: "aa-taxonomy-edit-action"/);
	assert.match(workspace, /className: "aa-taxonomy-delete-action"/);
	assert.match(workspace, /deleteCategoryTitle/);
	assert.match(workspace, /confirmLabel: t\("aaalice\.common\.delete"/);
	assert.match(workspace, /variant: "danger"/);
	assert.match(uiStyles, /\.aa-ui-button--danger/);
	const saveBody = workspace.match(/const saveItem = async[\s\S]*?\n\t};/)?.[0] || "";
	assert.match(saveBody, /updateCategory/);
	assert.doesNotMatch(saveBody, /deleteCategory|deleteCollection/);
	const removeBody = workspace.match(/const remove = async[\s\S]*?\n\t};/)?.[0] || "";
	assert.match(removeBody, /deleteCategory/);
	assert.match(removeBody, /danger: true/);
});

test("import and export use one reusable review flow with explicit outcomes", () => {
	assert.match(components, /export function createTransferHero/);
	assert.match(components, /export function createTransferStats/);
	assert.match(components, /export function createTransferSection/);
	assert.match(components, /export function createTransferResult/);
	assert.match(workspace, /function openLibraryExport/);
	assert.match(workspace, /function openDashboardExport/);
	assert.match(workspace, /createTransferSection\(\{ title: t\("aaalice\.workspace\.transfer\.conflictDecisions"/);
	assert.match(workspace, /disabled: groups\.invalid\.length > 0/);
	assert.match(workspace, /presetNeedsReview/);
	assert.match(workspace, /availableDashboardPresetName\(file\.name\)/);
	assert.match(workspace, /createDashboardPreset\(dashboardPresetState\(\), presetName\.value, snapshot\)/);
	assert.match(workspace, /createTransferResult\(\{ title: t\("aaalice\.workspace\.transfer\.importComplete"/);
	assert.match(libraryStore, /importPreflight\(file, \{ signal \} = \{\}\)/);
	assert.match(libraryStore, /importApply\(token, resolutions = \{\}, \{ signal \} = \{\}\)/);
	assert.match(libraryStore, /discardImport\(token\)/);
	assert.match(libraryStore, /apiURL\(`\$\{ENDPOINT\}\/export\/\$\{encodeURIComponent\(result\.token\)\}`\)/);
	assert.doesNotMatch(workspace, /response\.blob\(\)/);
	assert.match(theme, /\.aa-transfer-scope\.is-selected/);
	assert.match(theme, /\.aa-transfer-section\[open\] > summary > \.aa-ui-icon/);
	assert.match(theme, /@keyframes aa-transfer-loading/);
});

test("dashboard column projection re-renders when sidebar width crosses the breakpoint", () => {
	assert.match(workspace, /dashboardColumnsForWidth\(container\.clientWidth\)/);
	assert.match(workspace, /new ResizeObserver\(\(\) => \{/);
	assert.match(workspace, /dashboardColumnsForWidth\(element\.clientWidth\)/);
	assert.match(workspace, /if \(next === lastColumnBucket\) return;/);
	assert.match(workspace, /widthObserver\.observe\(element\)/);
	assert.match(workspace, /workspaceWidthObservers\.get\(element\)\?\.disconnect\(\)/);
	assert.match(workspace, /workspaceWidthObservers\.delete\(element\)/);
	assert.match(dashboardSizing, /export function dashboardColumnsForWidth/);
	assert.match(dashboardSizing, /DASHBOARD_SINGLE_COLUMN_MAX_WIDTH = 330/);
});

test("sidebar tab remounts triggered by reactive value writes never interrupt an active gesture", () => {
	assert.match(workspaceControls, /activeControlGestures \+= 1/);
	assert.match(workspaceControls, /activeControlGestures = Math\.max\(0, activeControlGestures - 1\)/);
	assert.match(workspaceControls, /export function hasActiveControlGestures/);
	assert.match(workspace, /renderedWorkspaceTabs\.has\(element\)/);
	assert.match(workspace, /if \(!hasActiveControlGestures\(\)\) scheduleRender\(\);/);
	assert.match(workspace, /renderedWorkspaceTabs\.add\(element\); renderWorkspace\(element\);/);
});
